package client

import (
	"context"
	"net/http"
	"net/url"
)

// AuthClient provides auth-management API operations.
type AuthClient interface {
	// CreateOIDCProvisioningRule creates an OIDC provisioning rule.
	CreateOIDCProvisioningRule(context.Context, SaveOIDCProvisioningRuleRequest) (OIDCProvisioningRule, error)

	// ListOIDCProvisioningRules returns configured OIDC provisioning rules.
	ListOIDCProvisioningRules(context.Context) ([]OIDCProvisioningRule, error)

	// GetOIDCProvisioningRule returns one OIDC provisioning rule.
	GetOIDCProvisioningRule(context.Context, string) (OIDCProvisioningRule, error)

	// UpdateOIDCProvisioningRule replaces one OIDC provisioning rule.
	UpdateOIDCProvisioningRule(
		context.Context,
		string,
		SaveOIDCProvisioningRuleRequest,
	) (OIDCProvisioningRule, error)

	// DeleteOIDCProvisioningRule deletes one OIDC provisioning rule.
	DeleteOIDCProvisioningRule(context.Context, string) error
}

// HTTPAuthClient is the concrete HTTP implementation of AuthClient.
type HTTPAuthClient struct {
	// transport carries the HTTP configuration shared with the parent Client.
	transport *transport
}

var _ AuthClient = (*HTTPAuthClient)(nil)

// SaveOIDCProvisioningRuleRequest creates or updates an OIDC provisioning rule.
type SaveOIDCProvisioningRuleRequest struct {
	// ID is the stable rule identifier. Empty IDs are generated by the server on create.
	ID string `json:"id,omitempty"`

	// DisplayName is the operator-facing rule label.
	DisplayName string `json:"display_name"`

	// IssuerURL is the trusted OIDC issuer URL.
	IssuerURL string `json:"issuer_url"`

	// Audience is the accepted JWT audience.
	Audience string `json:"audience"`

	// ForwardedClaims are top-level verified JWT claims exposed to the CEL condition.
	ForwardedClaims []string `json:"forwarded_claims,omitempty"`

	// Condition is the CEL bool expression evaluated during provisioning.
	Condition string `json:"condition"`

	// Enabled controls whether the rule participates in provisioning.
	Enabled *bool `json:"enabled,omitempty"`
}

// OIDCProvisioningRule describes an operator-managed OIDC provisioning rule.
type OIDCProvisioningRule struct {
	// ID is the stable rule identifier.
	ID string `json:"id"`

	// DisplayName is the operator-facing rule label.
	DisplayName string `json:"display_name"`

	// IssuerURL is the trusted OIDC issuer URL.
	IssuerURL string `json:"issuer_url"`

	// Audience is the accepted JWT audience.
	Audience string `json:"audience"`

	// ForwardedClaims are top-level verified JWT claims exposed to the CEL condition.
	ForwardedClaims []string `json:"forwarded_claims,omitempty"`

	// Condition is the CEL bool expression evaluated during provisioning.
	Condition string `json:"condition"`

	// AssignRoleIDs are local role IDs assigned when Condition matches.
	AssignRoleIDs []string `json:"assign_role_ids"`

	// Enabled controls whether the rule participates in provisioning.
	Enabled bool `json:"enabled"`
}

type oidcProvisioningRuleList struct {
	Rules []OIDCProvisioningRule `json:"rules"`
}

// newHTTPAuthClient binds an auth-management operation group to the shared transport.
func newHTTPAuthClient(transport *transport) *HTTPAuthClient {
	return &HTTPAuthClient{transport: transport}
}

// CreateOIDCProvisioningRule creates an OIDC provisioning rule.
func (client *HTTPAuthClient) CreateOIDCProvisioningRule(
	ctx context.Context,
	request SaveOIDCProvisioningRuleRequest,
) (OIDCProvisioningRule, error) {
	var rule OIDCProvisioningRule
	err := client.transport.doJSON(
		ctx,
		"/v1/auth/oidc-provisioning-rules",
		request,
		http.StatusCreated,
		&rule,
	)

	return rule, err
}

// ListOIDCProvisioningRules returns configured OIDC provisioning rules.
func (client *HTTPAuthClient) ListOIDCProvisioningRules(
	ctx context.Context,
) ([]OIDCProvisioningRule, error) {
	var list oidcProvisioningRuleList
	err := client.transport.do(
		ctx,
		http.MethodGet,
		"/v1/auth/oidc-provisioning-rules",
		nil,
		0,
		nil,
		&list,
	)

	return list.Rules, err
}

// GetOIDCProvisioningRule returns one OIDC provisioning rule.
func (client *HTTPAuthClient) GetOIDCProvisioningRule(
	ctx context.Context,
	ruleID string,
) (OIDCProvisioningRule, error) {
	var rule OIDCProvisioningRule
	err := client.transport.do(
		ctx,
		http.MethodGet,
		"/v1/auth/oidc-provisioning-rules/"+url.PathEscape(ruleID),
		nil,
		0,
		nil,
		&rule,
	)

	return rule, err
}

// UpdateOIDCProvisioningRule replaces one OIDC provisioning rule.
func (client *HTTPAuthClient) UpdateOIDCProvisioningRule(
	ctx context.Context,
	ruleID string,
	request SaveOIDCProvisioningRuleRequest,
) (OIDCProvisioningRule, error) {
	var rule OIDCProvisioningRule
	err := client.transport.doJSONMethod(
		ctx,
		http.MethodPut,
		"/v1/auth/oidc-provisioning-rules/"+url.PathEscape(ruleID),
		request,
		http.StatusOK,
		&rule,
	)

	return rule, err
}

// DeleteOIDCProvisioningRule deletes one OIDC provisioning rule.
func (client *HTTPAuthClient) DeleteOIDCProvisioningRule(ctx context.Context, ruleID string) error {
	resp, err := client.transport.doResponse(
		ctx,
		http.MethodDelete,
		"/v1/auth/oidc-provisioning-rules/"+url.PathEscape(ruleID),
		nil,
		0,
		nil,
		http.StatusNoContent,
	)
	if err != nil {
		return err
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	return nil
}
