// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/uploads"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AbortSession provides a mock function for the type MockStore
func (_mock *MockStore) AbortSession(context1 context.Context, abortSessionParams uploads.AbortSessionParams) (uploads.Session, error) {
	ret := _mock.Called(context1, abortSessionParams)

	if len(ret) == 0 {
		panic("no return value specified for AbortSession")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortSessionParams) (uploads.Session, error)); ok {
		return returnFunc(context1, abortSessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortSessionParams) uploads.Session); ok {
		r0 = returnFunc(context1, abortSessionParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.AbortSessionParams) error); ok {
		r1 = returnFunc(context1, abortSessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AbortSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortSession'
type MockStore_AbortSession_Call struct {
	*mock.Call
}

// AbortSession is a helper method to define mock.On call
//   - context1 context.Context
//   - abortSessionParams uploads.AbortSessionParams
func (_e *MockStore_Expecter) AbortSession(context1 interface{}, abortSessionParams interface{}) *MockStore_AbortSession_Call {
	return &MockStore_AbortSession_Call{Call: _e.mock.On("AbortSession", context1, abortSessionParams)}
}

func (_c *MockStore_AbortSession_Call) Run(run func(context1 context.Context, abortSessionParams uploads.AbortSessionParams)) *MockStore_AbortSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.AbortSessionParams
		if args[1] != nil {
			arg1 = args[1].(uploads.AbortSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AbortSession_Call) Return(session uploads.Session, err error) *MockStore_AbortSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_AbortSession_Call) RunAndReturn(run func(context1 context.Context, abortSessionParams uploads.AbortSessionParams) (uploads.Session, error)) *MockStore_AbortSession_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimIngestJob provides a mock function for the type MockStore
func (_mock *MockStore) ClaimIngestJob(context1 context.Context, claimIngestJobParams uploads.ClaimIngestJobParams) (uploads.IngestJob, error) {
	ret := _mock.Called(context1, claimIngestJobParams)

	if len(ret) == 0 {
		panic("no return value specified for ClaimIngestJob")
	}

	var r0 uploads.IngestJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.ClaimIngestJobParams) (uploads.IngestJob, error)); ok {
		return returnFunc(context1, claimIngestJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.ClaimIngestJobParams) uploads.IngestJob); ok {
		r0 = returnFunc(context1, claimIngestJobParams)
	} else {
		r0 = ret.Get(0).(uploads.IngestJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.ClaimIngestJobParams) error); ok {
		r1 = returnFunc(context1, claimIngestJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ClaimIngestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimIngestJob'
type MockStore_ClaimIngestJob_Call struct {
	*mock.Call
}

// ClaimIngestJob is a helper method to define mock.On call
//   - context1 context.Context
//   - claimIngestJobParams uploads.ClaimIngestJobParams
func (_e *MockStore_Expecter) ClaimIngestJob(context1 interface{}, claimIngestJobParams interface{}) *MockStore_ClaimIngestJob_Call {
	return &MockStore_ClaimIngestJob_Call{Call: _e.mock.On("ClaimIngestJob", context1, claimIngestJobParams)}
}

func (_c *MockStore_ClaimIngestJob_Call) Run(run func(context1 context.Context, claimIngestJobParams uploads.ClaimIngestJobParams)) *MockStore_ClaimIngestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.ClaimIngestJobParams
		if args[1] != nil {
			arg1 = args[1].(uploads.ClaimIngestJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ClaimIngestJob_Call) Return(ingestJob uploads.IngestJob, err error) *MockStore_ClaimIngestJob_Call {
	_c.Call.Return(ingestJob, err)
	return _c
}

func (_c *MockStore_ClaimIngestJob_Call) RunAndReturn(run func(context1 context.Context, claimIngestJobParams uploads.ClaimIngestJobParams) (uploads.IngestJob, error)) *MockStore_ClaimIngestJob_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteSession provides a mock function for the type MockStore
func (_mock *MockStore) CompleteSession(context1 context.Context, completeSessionParams uploads.CompleteSessionParams) (uploads.Session, error) {
	ret := _mock.Called(context1, completeSessionParams)

	if len(ret) == 0 {
		panic("no return value specified for CompleteSession")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteSessionParams) (uploads.Session, error)); ok {
		return returnFunc(context1, completeSessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteSessionParams) uploads.Session); ok {
		r0 = returnFunc(context1, completeSessionParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.CompleteSessionParams) error); ok {
		r1 = returnFunc(context1, completeSessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CompleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteSession'
type MockStore_CompleteSession_Call struct {
	*mock.Call
}

// CompleteSession is a helper method to define mock.On call
//   - context1 context.Context
//   - completeSessionParams uploads.CompleteSessionParams
func (_e *MockStore_Expecter) CompleteSession(context1 interface{}, completeSessionParams interface{}) *MockStore_CompleteSession_Call {
	return &MockStore_CompleteSession_Call{Call: _e.mock.On("CompleteSession", context1, completeSessionParams)}
}

func (_c *MockStore_CompleteSession_Call) Run(run func(context1 context.Context, completeSessionParams uploads.CompleteSessionParams)) *MockStore_CompleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.CompleteSessionParams
		if args[1] != nil {
			arg1 = args[1].(uploads.CompleteSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CompleteSession_Call) Return(session uploads.Session, err error) *MockStore_CompleteSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_CompleteSession_Call) RunAndReturn(run func(context1 context.Context, completeSessionParams uploads.CompleteSessionParams) (uploads.Session, error)) *MockStore_CompleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReadySession provides a mock function for the type MockStore
func (_mock *MockStore) CreateReadySession(context1 context.Context, createReadySessionParams uploads.CreateReadySessionParams) (uploads.Session, error) {
	ret := _mock.Called(context1, createReadySessionParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateReadySession")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CreateReadySessionParams) (uploads.Session, error)); ok {
		return returnFunc(context1, createReadySessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CreateReadySessionParams) uploads.Session); ok {
		r0 = returnFunc(context1, createReadySessionParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.CreateReadySessionParams) error); ok {
		r1 = returnFunc(context1, createReadySessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateReadySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReadySession'
type MockStore_CreateReadySession_Call struct {
	*mock.Call
}

// CreateReadySession is a helper method to define mock.On call
//   - context1 context.Context
//   - createReadySessionParams uploads.CreateReadySessionParams
func (_e *MockStore_Expecter) CreateReadySession(context1 interface{}, createReadySessionParams interface{}) *MockStore_CreateReadySession_Call {
	return &MockStore_CreateReadySession_Call{Call: _e.mock.On("CreateReadySession", context1, createReadySessionParams)}
}

func (_c *MockStore_CreateReadySession_Call) Run(run func(context1 context.Context, createReadySessionParams uploads.CreateReadySessionParams)) *MockStore_CreateReadySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.CreateReadySessionParams
		if args[1] != nil {
			arg1 = args[1].(uploads.CreateReadySessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateReadySession_Call) Return(session uploads.Session, err error) *MockStore_CreateReadySession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_CreateReadySession_Call) RunAndReturn(run func(context1 context.Context, createReadySessionParams uploads.CreateReadySessionParams) (uploads.Session, error)) *MockStore_CreateReadySession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockStore
func (_mock *MockStore) CreateSession(context1 context.Context, createSessionParams uploads.CreateSessionParams) (uploads.Session, error) {
	ret := _mock.Called(context1, createSessionParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CreateSessionParams) (uploads.Session, error)); ok {
		return returnFunc(context1, createSessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CreateSessionParams) uploads.Session); ok {
		r0 = returnFunc(context1, createSessionParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.CreateSessionParams) error); ok {
		r1 = returnFunc(context1, createSessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - context1 context.Context
//   - createSessionParams uploads.CreateSessionParams
func (_e *MockStore_Expecter) CreateSession(context1 interface{}, createSessionParams interface{}) *MockStore_CreateSession_Call {
	return &MockStore_CreateSession_Call{Call: _e.mock.On("CreateSession", context1, createSessionParams)}
}

func (_c *MockStore_CreateSession_Call) Run(run func(context1 context.Context, createSessionParams uploads.CreateSessionParams)) *MockStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(uploads.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateSession_Call) Return(session uploads.Session, err error) *MockStore_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_CreateSession_Call) RunAndReturn(run func(context1 context.Context, createSessionParams uploads.CreateSessionParams) (uploads.Session, error)) *MockStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// FailIngestJob provides a mock function for the type MockStore
func (_mock *MockStore) FailIngestJob(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams) (uploads.IngestJob, error) {
	ret := _mock.Called(context1, failIngestJobParams)

	if len(ret) == 0 {
		panic("no return value specified for FailIngestJob")
	}

	var r0 uploads.IngestJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.FailIngestJobParams) (uploads.IngestJob, error)); ok {
		return returnFunc(context1, failIngestJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.FailIngestJobParams) uploads.IngestJob); ok {
		r0 = returnFunc(context1, failIngestJobParams)
	} else {
		r0 = ret.Get(0).(uploads.IngestJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.FailIngestJobParams) error); ok {
		r1 = returnFunc(context1, failIngestJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_FailIngestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailIngestJob'
type MockStore_FailIngestJob_Call struct {
	*mock.Call
}

// FailIngestJob is a helper method to define mock.On call
//   - context1 context.Context
//   - failIngestJobParams uploads.FailIngestJobParams
func (_e *MockStore_Expecter) FailIngestJob(context1 interface{}, failIngestJobParams interface{}) *MockStore_FailIngestJob_Call {
	return &MockStore_FailIngestJob_Call{Call: _e.mock.On("FailIngestJob", context1, failIngestJobParams)}
}

func (_c *MockStore_FailIngestJob_Call) Run(run func(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams)) *MockStore_FailIngestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.FailIngestJobParams
		if args[1] != nil {
			arg1 = args[1].(uploads.FailIngestJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_FailIngestJob_Call) Return(ingestJob uploads.IngestJob, err error) *MockStore_FailIngestJob_Call {
	_c.Call.Return(ingestJob, err)
	return _c
}

func (_c *MockStore_FailIngestJob_Call) RunAndReturn(run func(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams) (uploads.IngestJob, error)) *MockStore_FailIngestJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockStore
func (_mock *MockStore) GetSession(context1 context.Context, getSessionParams uploads.GetSessionParams) (uploads.Session, error) {
	ret := _mock.Called(context1, getSessionParams)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetSessionParams) (uploads.Session, error)); ok {
		return returnFunc(context1, getSessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetSessionParams) uploads.Session); ok {
		r0 = returnFunc(context1, getSessionParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.GetSessionParams) error); ok {
		r1 = returnFunc(context1, getSessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - context1 context.Context
//   - getSessionParams uploads.GetSessionParams
func (_e *MockStore_Expecter) GetSession(context1 interface{}, getSessionParams interface{}) *MockStore_GetSession_Call {
	return &MockStore_GetSession_Call{Call: _e.mock.On("GetSession", context1, getSessionParams)}
}

func (_c *MockStore_GetSession_Call) Run(run func(context1 context.Context, getSessionParams uploads.GetSessionParams)) *MockStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.GetSessionParams
		if args[1] != nil {
			arg1 = args[1].(uploads.GetSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetSession_Call) Return(session uploads.Session, err error) *MockStore_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_GetSession_Call) RunAndReturn(run func(context1 context.Context, getSessionParams uploads.GetSessionParams) (uploads.Session, error)) *MockStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// PutPart provides a mock function for the type MockStore
func (_mock *MockStore) PutPart(context1 context.Context, putPartParams uploads.PutPartParams) (uploads.Part, error) {
	ret := _mock.Called(context1, putPartParams)

	if len(ret) == 0 {
		panic("no return value specified for PutPart")
	}

	var r0 uploads.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutPartParams) (uploads.Part, error)); ok {
		return returnFunc(context1, putPartParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutPartParams) uploads.Part); ok {
		r0 = returnFunc(context1, putPartParams)
	} else {
		r0 = ret.Get(0).(uploads.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.PutPartParams) error); ok {
		r1 = returnFunc(context1, putPartParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PutPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPart'
type MockStore_PutPart_Call struct {
	*mock.Call
}

// PutPart is a helper method to define mock.On call
//   - context1 context.Context
//   - putPartParams uploads.PutPartParams
func (_e *MockStore_Expecter) PutPart(context1 interface{}, putPartParams interface{}) *MockStore_PutPart_Call {
	return &MockStore_PutPart_Call{Call: _e.mock.On("PutPart", context1, putPartParams)}
}

func (_c *MockStore_PutPart_Call) Run(run func(context1 context.Context, putPartParams uploads.PutPartParams)) *MockStore_PutPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.PutPartParams
		if args[1] != nil {
			arg1 = args[1].(uploads.PutPartParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutPart_Call) Return(part uploads.Part, err error) *MockStore_PutPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockStore_PutPart_Call) RunAndReturn(run func(context1 context.Context, putPartParams uploads.PutPartParams) (uploads.Part, error)) *MockStore_PutPart_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedIngestJob provides a mock function for the type MockStore
func (_mock *MockStore) SucceedIngestJob(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams) (uploads.IngestJob, error) {
	ret := _mock.Called(context1, succeedIngestJobParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedIngestJob")
	}

	var r0 uploads.IngestJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.SucceedIngestJobParams) (uploads.IngestJob, error)); ok {
		return returnFunc(context1, succeedIngestJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.SucceedIngestJobParams) uploads.IngestJob); ok {
		r0 = returnFunc(context1, succeedIngestJobParams)
	} else {
		r0 = ret.Get(0).(uploads.IngestJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.SucceedIngestJobParams) error); ok {
		r1 = returnFunc(context1, succeedIngestJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SucceedIngestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedIngestJob'
type MockStore_SucceedIngestJob_Call struct {
	*mock.Call
}

// SucceedIngestJob is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedIngestJobParams uploads.SucceedIngestJobParams
func (_e *MockStore_Expecter) SucceedIngestJob(context1 interface{}, succeedIngestJobParams interface{}) *MockStore_SucceedIngestJob_Call {
	return &MockStore_SucceedIngestJob_Call{Call: _e.mock.On("SucceedIngestJob", context1, succeedIngestJobParams)}
}

func (_c *MockStore_SucceedIngestJob_Call) Run(run func(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams)) *MockStore_SucceedIngestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.SucceedIngestJobParams
		if args[1] != nil {
			arg1 = args[1].(uploads.SucceedIngestJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SucceedIngestJob_Call) Return(ingestJob uploads.IngestJob, err error) *MockStore_SucceedIngestJob_Call {
	_c.Call.Return(ingestJob, err)
	return _c
}

func (_c *MockStore_SucceedIngestJob_Call) RunAndReturn(run func(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams) (uploads.IngestJob, error)) *MockStore_SucceedIngestJob_Call {
	_c.Call.Return(run)
	return _c
}
