// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/materialization/incus"
	"github.com/meigma/imgsrv/internal/publish"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStepStore creates a new instance of MockStepStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepStore {
	mock := &MockStepStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStepStore is an autogenerated mock type for the StepStore type
type MockStepStore struct {
	mock.Mock
}

type MockStepStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepStore) EXPECT() *MockStepStore_Expecter {
	return &MockStepStore_Expecter{mock: &_m.Mock}
}

// ClaimStep provides a mock function for the type MockStepStore
func (_mock *MockStepStore) ClaimStep(context1 context.Context, claimStepParams publish.ClaimStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, claimStepParams)

	if len(ret) == 0 {
		panic("no return value specified for ClaimStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.ClaimStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, claimStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.ClaimStepParams) publish.Step); ok {
		r0 = returnFunc(context1, claimStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.ClaimStepParams) error); ok {
		r1 = returnFunc(context1, claimStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepStore_ClaimStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimStep'
type MockStepStore_ClaimStep_Call struct {
	*mock.Call
}

// ClaimStep is a helper method to define mock.On call
//   - context1 context.Context
//   - claimStepParams publish.ClaimStepParams
func (_e *MockStepStore_Expecter) ClaimStep(context1 interface{}, claimStepParams interface{}) *MockStepStore_ClaimStep_Call {
	return &MockStepStore_ClaimStep_Call{Call: _e.mock.On("ClaimStep", context1, claimStepParams)}
}

func (_c *MockStepStore_ClaimStep_Call) Run(run func(context1 context.Context, claimStepParams publish.ClaimStepParams)) *MockStepStore_ClaimStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.ClaimStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.ClaimStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepStore_ClaimStep_Call) Return(step publish.Step, err error) *MockStepStore_ClaimStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStepStore_ClaimStep_Call) RunAndReturn(run func(context1 context.Context, claimStepParams publish.ClaimStepParams) (publish.Step, error)) *MockStepStore_ClaimStep_Call {
	_c.Call.Return(run)
	return _c
}

// FailStep provides a mock function for the type MockStepStore
func (_mock *MockStepStore) FailStep(context1 context.Context, failStepParams publish.FailStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, failStepParams)

	if len(ret) == 0 {
		panic("no return value specified for FailStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.FailStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, failStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.FailStepParams) publish.Step); ok {
		r0 = returnFunc(context1, failStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.FailStepParams) error); ok {
		r1 = returnFunc(context1, failStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepStore_FailStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailStep'
type MockStepStore_FailStep_Call struct {
	*mock.Call
}

// FailStep is a helper method to define mock.On call
//   - context1 context.Context
//   - failStepParams publish.FailStepParams
func (_e *MockStepStore_Expecter) FailStep(context1 interface{}, failStepParams interface{}) *MockStepStore_FailStep_Call {
	return &MockStepStore_FailStep_Call{Call: _e.mock.On("FailStep", context1, failStepParams)}
}

func (_c *MockStepStore_FailStep_Call) Run(run func(context1 context.Context, failStepParams publish.FailStepParams)) *MockStepStore_FailStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.FailStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.FailStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepStore_FailStep_Call) Return(step publish.Step, err error) *MockStepStore_FailStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStepStore_FailStep_Call) RunAndReturn(run func(context1 context.Context, failStepParams publish.FailStepParams) (publish.Step, error)) *MockStepStore_FailStep_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizePublishStep provides a mock function for the type MockStepStore
func (_mock *MockStepStore) FinalizePublishStep(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Job, error) {
	ret := _mock.Called(context1, succeedStepParams)

	if len(ret) == 0 {
		panic("no return value specified for FinalizePublishStep")
	}

	var r0 publish.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) (publish.Job, error)); ok {
		return returnFunc(context1, succeedStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) publish.Job); ok {
		r0 = returnFunc(context1, succeedStepParams)
	} else {
		r0 = ret.Get(0).(publish.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedStepParams) error); ok {
		r1 = returnFunc(context1, succeedStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepStore_FinalizePublishStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizePublishStep'
type MockStepStore_FinalizePublishStep_Call struct {
	*mock.Call
}

// FinalizePublishStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedStepParams publish.SucceedStepParams
func (_e *MockStepStore_Expecter) FinalizePublishStep(context1 interface{}, succeedStepParams interface{}) *MockStepStore_FinalizePublishStep_Call {
	return &MockStepStore_FinalizePublishStep_Call{Call: _e.mock.On("FinalizePublishStep", context1, succeedStepParams)}
}

func (_c *MockStepStore_FinalizePublishStep_Call) Run(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams)) *MockStepStore_FinalizePublishStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepStore_FinalizePublishStep_Call) Return(job publish.Job, err error) *MockStepStore_FinalizePublishStep_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockStepStore_FinalizePublishStep_Call) RunAndReturn(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Job, error)) *MockStepStore_FinalizePublishStep_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedIncusIndexStep provides a mock function for the type MockStepStore
func (_mock *MockStepStore) SucceedIncusIndexStep(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, succeedIncusIndexStepParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedIncusIndexStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedIncusIndexStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, succeedIncusIndexStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedIncusIndexStepParams) publish.Step); ok {
		r0 = returnFunc(context1, succeedIncusIndexStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedIncusIndexStepParams) error); ok {
		r1 = returnFunc(context1, succeedIncusIndexStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepStore_SucceedIncusIndexStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedIncusIndexStep'
type MockStepStore_SucceedIncusIndexStep_Call struct {
	*mock.Call
}

// SucceedIncusIndexStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams
func (_e *MockStepStore_Expecter) SucceedIncusIndexStep(context1 interface{}, succeedIncusIndexStepParams interface{}) *MockStepStore_SucceedIncusIndexStep_Call {
	return &MockStepStore_SucceedIncusIndexStep_Call{Call: _e.mock.On("SucceedIncusIndexStep", context1, succeedIncusIndexStepParams)}
}

func (_c *MockStepStore_SucceedIncusIndexStep_Call) Run(run func(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams)) *MockStepStore_SucceedIncusIndexStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedIncusIndexStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedIncusIndexStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepStore_SucceedIncusIndexStep_Call) Return(step publish.Step, err error) *MockStepStore_SucceedIncusIndexStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStepStore_SucceedIncusIndexStep_Call) RunAndReturn(run func(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams) (publish.Step, error)) *MockStepStore_SucceedIncusIndexStep_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedValidateCatalogStep provides a mock function for the type MockStepStore
func (_mock *MockStepStore) SucceedValidateCatalogStep(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, succeedStepParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedValidateCatalogStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, succeedStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) publish.Step); ok {
		r0 = returnFunc(context1, succeedStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedStepParams) error); ok {
		r1 = returnFunc(context1, succeedStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStepStore_SucceedValidateCatalogStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedValidateCatalogStep'
type MockStepStore_SucceedValidateCatalogStep_Call struct {
	*mock.Call
}

// SucceedValidateCatalogStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedStepParams publish.SucceedStepParams
func (_e *MockStepStore_Expecter) SucceedValidateCatalogStep(context1 interface{}, succeedStepParams interface{}) *MockStepStore_SucceedValidateCatalogStep_Call {
	return &MockStepStore_SucceedValidateCatalogStep_Call{Call: _e.mock.On("SucceedValidateCatalogStep", context1, succeedStepParams)}
}

func (_c *MockStepStore_SucceedValidateCatalogStep_Call) Run(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams)) *MockStepStore_SucceedValidateCatalogStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStepStore_SucceedValidateCatalogStep_Call) Return(step publish.Step, err error) *MockStepStore_SucceedValidateCatalogStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStepStore_SucceedValidateCatalogStep_Call) RunAndReturn(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Step, error)) *MockStepStore_SucceedValidateCatalogStep_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncusIndexer creates a new instance of MockIncusIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncusIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncusIndexer {
	mock := &MockIncusIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncusIndexer is an autogenerated mock type for the IncusIndexer type
type MockIncusIndexer struct {
	mock.Mock
}

type MockIncusIndexer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncusIndexer) EXPECT() *MockIncusIndexer_Expecter {
	return &MockIncusIndexer_Expecter{mock: &_m.Mock}
}

// IndexVersion provides a mock function for the type MockIncusIndexer
func (_mock *MockIncusIndexer) IndexVersion(context1 context.Context, indexVersionParams incus.IndexVersionParams) ([]incus.ProjectionRow, error) {
	ret := _mock.Called(context1, indexVersionParams)

	if len(ret) == 0 {
		panic("no return value specified for IndexVersion")
	}

	var r0 []incus.ProjectionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, incus.IndexVersionParams) ([]incus.ProjectionRow, error)); ok {
		return returnFunc(context1, indexVersionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, incus.IndexVersionParams) []incus.ProjectionRow); ok {
		r0 = returnFunc(context1, indexVersionParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]incus.ProjectionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, incus.IndexVersionParams) error); ok {
		r1 = returnFunc(context1, indexVersionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncusIndexer_IndexVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexVersion'
type MockIncusIndexer_IndexVersion_Call struct {
	*mock.Call
}

// IndexVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - indexVersionParams incus.IndexVersionParams
func (_e *MockIncusIndexer_Expecter) IndexVersion(context1 interface{}, indexVersionParams interface{}) *MockIncusIndexer_IndexVersion_Call {
	return &MockIncusIndexer_IndexVersion_Call{Call: _e.mock.On("IndexVersion", context1, indexVersionParams)}
}

func (_c *MockIncusIndexer_IndexVersion_Call) Run(run func(context1 context.Context, indexVersionParams incus.IndexVersionParams)) *MockIncusIndexer_IndexVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 incus.IndexVersionParams
		if args[1] != nil {
			arg1 = args[1].(incus.IndexVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncusIndexer_IndexVersion_Call) Return(projectionRows []incus.ProjectionRow, err error) *MockIncusIndexer_IndexVersion_Call {
	_c.Call.Return(projectionRows, err)
	return _c
}

func (_c *MockIncusIndexer_IndexVersion_Call) RunAndReturn(run func(context1 context.Context, indexVersionParams incus.IndexVersionParams) ([]incus.ProjectionRow, error)) *MockIncusIndexer_IndexVersion_Call {
	_c.Call.Return(run)
	return _c
}
