// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/publish"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// ClaimStep provides a mock function for the type MockStore
func (_mock *MockStore) ClaimStep(context1 context.Context, claimStepParams publish.ClaimStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, claimStepParams)

	if len(ret) == 0 {
		panic("no return value specified for ClaimStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.ClaimStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, claimStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.ClaimStepParams) publish.Step); ok {
		r0 = returnFunc(context1, claimStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.ClaimStepParams) error); ok {
		r1 = returnFunc(context1, claimStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ClaimStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimStep'
type MockStore_ClaimStep_Call struct {
	*mock.Call
}

// ClaimStep is a helper method to define mock.On call
//   - context1 context.Context
//   - claimStepParams publish.ClaimStepParams
func (_e *MockStore_Expecter) ClaimStep(context1 interface{}, claimStepParams interface{}) *MockStore_ClaimStep_Call {
	return &MockStore_ClaimStep_Call{Call: _e.mock.On("ClaimStep", context1, claimStepParams)}
}

func (_c *MockStore_ClaimStep_Call) Run(run func(context1 context.Context, claimStepParams publish.ClaimStepParams)) *MockStore_ClaimStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.ClaimStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.ClaimStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ClaimStep_Call) Return(step publish.Step, err error) *MockStore_ClaimStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStore_ClaimStep_Call) RunAndReturn(run func(context1 context.Context, claimStepParams publish.ClaimStepParams) (publish.Step, error)) *MockStore_ClaimStep_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueVersion provides a mock function for the type MockStore
func (_mock *MockStore) EnqueueVersion(context1 context.Context, enqueueVersionParams publish.EnqueueVersionParams) (publish.Job, error) {
	ret := _mock.Called(context1, enqueueVersionParams)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueVersion")
	}

	var r0 publish.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.EnqueueVersionParams) (publish.Job, error)); ok {
		return returnFunc(context1, enqueueVersionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.EnqueueVersionParams) publish.Job); ok {
		r0 = returnFunc(context1, enqueueVersionParams)
	} else {
		r0 = ret.Get(0).(publish.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.EnqueueVersionParams) error); ok {
		r1 = returnFunc(context1, enqueueVersionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_EnqueueVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueVersion'
type MockStore_EnqueueVersion_Call struct {
	*mock.Call
}

// EnqueueVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - enqueueVersionParams publish.EnqueueVersionParams
func (_e *MockStore_Expecter) EnqueueVersion(context1 interface{}, enqueueVersionParams interface{}) *MockStore_EnqueueVersion_Call {
	return &MockStore_EnqueueVersion_Call{Call: _e.mock.On("EnqueueVersion", context1, enqueueVersionParams)}
}

func (_c *MockStore_EnqueueVersion_Call) Run(run func(context1 context.Context, enqueueVersionParams publish.EnqueueVersionParams)) *MockStore_EnqueueVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.EnqueueVersionParams
		if args[1] != nil {
			arg1 = args[1].(publish.EnqueueVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_EnqueueVersion_Call) Return(job publish.Job, err error) *MockStore_EnqueueVersion_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockStore_EnqueueVersion_Call) RunAndReturn(run func(context1 context.Context, enqueueVersionParams publish.EnqueueVersionParams) (publish.Job, error)) *MockStore_EnqueueVersion_Call {
	_c.Call.Return(run)
	return _c
}

// FailStep provides a mock function for the type MockStore
func (_mock *MockStore) FailStep(context1 context.Context, failStepParams publish.FailStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, failStepParams)

	if len(ret) == 0 {
		panic("no return value specified for FailStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.FailStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, failStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.FailStepParams) publish.Step); ok {
		r0 = returnFunc(context1, failStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.FailStepParams) error); ok {
		r1 = returnFunc(context1, failStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_FailStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailStep'
type MockStore_FailStep_Call struct {
	*mock.Call
}

// FailStep is a helper method to define mock.On call
//   - context1 context.Context
//   - failStepParams publish.FailStepParams
func (_e *MockStore_Expecter) FailStep(context1 interface{}, failStepParams interface{}) *MockStore_FailStep_Call {
	return &MockStore_FailStep_Call{Call: _e.mock.On("FailStep", context1, failStepParams)}
}

func (_c *MockStore_FailStep_Call) Run(run func(context1 context.Context, failStepParams publish.FailStepParams)) *MockStore_FailStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.FailStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.FailStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_FailStep_Call) Return(step publish.Step, err error) *MockStore_FailStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStore_FailStep_Call) RunAndReturn(run func(context1 context.Context, failStepParams publish.FailStepParams) (publish.Step, error)) *MockStore_FailStep_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizePublishStep provides a mock function for the type MockStore
func (_mock *MockStore) FinalizePublishStep(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Job, error) {
	ret := _mock.Called(context1, succeedStepParams)

	if len(ret) == 0 {
		panic("no return value specified for FinalizePublishStep")
	}

	var r0 publish.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) (publish.Job, error)); ok {
		return returnFunc(context1, succeedStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) publish.Job); ok {
		r0 = returnFunc(context1, succeedStepParams)
	} else {
		r0 = ret.Get(0).(publish.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedStepParams) error); ok {
		r1 = returnFunc(context1, succeedStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_FinalizePublishStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizePublishStep'
type MockStore_FinalizePublishStep_Call struct {
	*mock.Call
}

// FinalizePublishStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedStepParams publish.SucceedStepParams
func (_e *MockStore_Expecter) FinalizePublishStep(context1 interface{}, succeedStepParams interface{}) *MockStore_FinalizePublishStep_Call {
	return &MockStore_FinalizePublishStep_Call{Call: _e.mock.On("FinalizePublishStep", context1, succeedStepParams)}
}

func (_c *MockStore_FinalizePublishStep_Call) Run(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams)) *MockStore_FinalizePublishStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_FinalizePublishStep_Call) Return(job publish.Job, err error) *MockStore_FinalizePublishStep_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockStore_FinalizePublishStep_Call) RunAndReturn(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Job, error)) *MockStore_FinalizePublishStep_Call {
	_c.Call.Return(run)
	return _c
}

// GetJob provides a mock function for the type MockStore
func (_mock *MockStore) GetJob(context1 context.Context, getJobParams publish.GetJobParams) (publish.Job, error) {
	ret := _mock.Called(context1, getJobParams)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 publish.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.GetJobParams) (publish.Job, error)); ok {
		return returnFunc(context1, getJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.GetJobParams) publish.Job); ok {
		r0 = returnFunc(context1, getJobParams)
	} else {
		r0 = ret.Get(0).(publish.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.GetJobParams) error); ok {
		r1 = returnFunc(context1, getJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockStore_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - context1 context.Context
//   - getJobParams publish.GetJobParams
func (_e *MockStore_Expecter) GetJob(context1 interface{}, getJobParams interface{}) *MockStore_GetJob_Call {
	return &MockStore_GetJob_Call{Call: _e.mock.On("GetJob", context1, getJobParams)}
}

func (_c *MockStore_GetJob_Call) Run(run func(context1 context.Context, getJobParams publish.GetJobParams)) *MockStore_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.GetJobParams
		if args[1] != nil {
			arg1 = args[1].(publish.GetJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetJob_Call) Return(job publish.Job, err error) *MockStore_GetJob_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockStore_GetJob_Call) RunAndReturn(run func(context1 context.Context, getJobParams publish.GetJobParams) (publish.Job, error)) *MockStore_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// RetryJob provides a mock function for the type MockStore
func (_mock *MockStore) RetryJob(context1 context.Context, retryJobParams publish.RetryJobParams) (publish.Job, error) {
	ret := _mock.Called(context1, retryJobParams)

	if len(ret) == 0 {
		panic("no return value specified for RetryJob")
	}

	var r0 publish.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.RetryJobParams) (publish.Job, error)); ok {
		return returnFunc(context1, retryJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.RetryJobParams) publish.Job); ok {
		r0 = returnFunc(context1, retryJobParams)
	} else {
		r0 = ret.Get(0).(publish.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.RetryJobParams) error); ok {
		r1 = returnFunc(context1, retryJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RetryJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryJob'
type MockStore_RetryJob_Call struct {
	*mock.Call
}

// RetryJob is a helper method to define mock.On call
//   - context1 context.Context
//   - retryJobParams publish.RetryJobParams
func (_e *MockStore_Expecter) RetryJob(context1 interface{}, retryJobParams interface{}) *MockStore_RetryJob_Call {
	return &MockStore_RetryJob_Call{Call: _e.mock.On("RetryJob", context1, retryJobParams)}
}

func (_c *MockStore_RetryJob_Call) Run(run func(context1 context.Context, retryJobParams publish.RetryJobParams)) *MockStore_RetryJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.RetryJobParams
		if args[1] != nil {
			arg1 = args[1].(publish.RetryJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_RetryJob_Call) Return(job publish.Job, err error) *MockStore_RetryJob_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockStore_RetryJob_Call) RunAndReturn(run func(context1 context.Context, retryJobParams publish.RetryJobParams) (publish.Job, error)) *MockStore_RetryJob_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedIncusIndexStep provides a mock function for the type MockStore
func (_mock *MockStore) SucceedIncusIndexStep(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, succeedIncusIndexStepParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedIncusIndexStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedIncusIndexStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, succeedIncusIndexStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedIncusIndexStepParams) publish.Step); ok {
		r0 = returnFunc(context1, succeedIncusIndexStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedIncusIndexStepParams) error); ok {
		r1 = returnFunc(context1, succeedIncusIndexStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SucceedIncusIndexStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedIncusIndexStep'
type MockStore_SucceedIncusIndexStep_Call struct {
	*mock.Call
}

// SucceedIncusIndexStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams
func (_e *MockStore_Expecter) SucceedIncusIndexStep(context1 interface{}, succeedIncusIndexStepParams interface{}) *MockStore_SucceedIncusIndexStep_Call {
	return &MockStore_SucceedIncusIndexStep_Call{Call: _e.mock.On("SucceedIncusIndexStep", context1, succeedIncusIndexStepParams)}
}

func (_c *MockStore_SucceedIncusIndexStep_Call) Run(run func(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams)) *MockStore_SucceedIncusIndexStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedIncusIndexStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedIncusIndexStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SucceedIncusIndexStep_Call) Return(step publish.Step, err error) *MockStore_SucceedIncusIndexStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStore_SucceedIncusIndexStep_Call) RunAndReturn(run func(context1 context.Context, succeedIncusIndexStepParams publish.SucceedIncusIndexStepParams) (publish.Step, error)) *MockStore_SucceedIncusIndexStep_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedValidateCatalogStep provides a mock function for the type MockStore
func (_mock *MockStore) SucceedValidateCatalogStep(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Step, error) {
	ret := _mock.Called(context1, succeedStepParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedValidateCatalogStep")
	}

	var r0 publish.Step
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) (publish.Step, error)); ok {
		return returnFunc(context1, succeedStepParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, publish.SucceedStepParams) publish.Step); ok {
		r0 = returnFunc(context1, succeedStepParams)
	} else {
		r0 = ret.Get(0).(publish.Step)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, publish.SucceedStepParams) error); ok {
		r1 = returnFunc(context1, succeedStepParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SucceedValidateCatalogStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedValidateCatalogStep'
type MockStore_SucceedValidateCatalogStep_Call struct {
	*mock.Call
}

// SucceedValidateCatalogStep is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedStepParams publish.SucceedStepParams
func (_e *MockStore_Expecter) SucceedValidateCatalogStep(context1 interface{}, succeedStepParams interface{}) *MockStore_SucceedValidateCatalogStep_Call {
	return &MockStore_SucceedValidateCatalogStep_Call{Call: _e.mock.On("SucceedValidateCatalogStep", context1, succeedStepParams)}
}

func (_c *MockStore_SucceedValidateCatalogStep_Call) Run(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams)) *MockStore_SucceedValidateCatalogStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 publish.SucceedStepParams
		if args[1] != nil {
			arg1 = args[1].(publish.SucceedStepParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SucceedValidateCatalogStep_Call) Return(step publish.Step, err error) *MockStore_SucceedValidateCatalogStep_Call {
	_c.Call.Return(step, err)
	return _c
}

func (_c *MockStore_SucceedValidateCatalogStep_Call) RunAndReturn(run func(context1 context.Context, succeedStepParams publish.SucceedStepParams) (publish.Step, error)) *MockStore_SucceedValidateCatalogStep_Call {
	_c.Call.Return(run)
	return _c
}
