// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockStore
func (_mock *MockStore) CreateToken(context1 context.Context, createTokenParams auth.CreateTokenParams) (auth.Token, error) {
	ret := _mock.Called(context1, createTokenParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 auth.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateTokenParams) (auth.Token, error)); ok {
		return returnFunc(context1, createTokenParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateTokenParams) auth.Token); ok {
		r0 = returnFunc(context1, createTokenParams)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.CreateTokenParams) error); ok {
		r1 = returnFunc(context1, createTokenParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockStore_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - context1 context.Context
//   - createTokenParams auth.CreateTokenParams
func (_e *MockStore_Expecter) CreateToken(context1 interface{}, createTokenParams interface{}) *MockStore_CreateToken_Call {
	return &MockStore_CreateToken_Call{Call: _e.mock.On("CreateToken", context1, createTokenParams)}
}

func (_c *MockStore_CreateToken_Call) Run(run func(context1 context.Context, createTokenParams auth.CreateTokenParams)) *MockStore_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.CreateTokenParams
		if args[1] != nil {
			arg1 = args[1].(auth.CreateTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateToken_Call) Return(token auth.Token, err error) *MockStore_CreateToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockStore_CreateToken_Call) RunAndReturn(run func(context1 context.Context, createTokenParams auth.CreateTokenParams) (auth.Token, error)) *MockStore_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// LookupActiveToken provides a mock function for the type MockStore
func (_mock *MockStore) LookupActiveToken(context1 context.Context, lookupActiveTokenParams auth.LookupActiveTokenParams) (auth.Token, error) {
	ret := _mock.Called(context1, lookupActiveTokenParams)

	if len(ret) == 0 {
		panic("no return value specified for LookupActiveToken")
	}

	var r0 auth.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LookupActiveTokenParams) (auth.Token, error)); ok {
		return returnFunc(context1, lookupActiveTokenParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LookupActiveTokenParams) auth.Token); ok {
		r0 = returnFunc(context1, lookupActiveTokenParams)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.LookupActiveTokenParams) error); ok {
		r1 = returnFunc(context1, lookupActiveTokenParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_LookupActiveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupActiveToken'
type MockStore_LookupActiveToken_Call struct {
	*mock.Call
}

// LookupActiveToken is a helper method to define mock.On call
//   - context1 context.Context
//   - lookupActiveTokenParams auth.LookupActiveTokenParams
func (_e *MockStore_Expecter) LookupActiveToken(context1 interface{}, lookupActiveTokenParams interface{}) *MockStore_LookupActiveToken_Call {
	return &MockStore_LookupActiveToken_Call{Call: _e.mock.On("LookupActiveToken", context1, lookupActiveTokenParams)}
}

func (_c *MockStore_LookupActiveToken_Call) Run(run func(context1 context.Context, lookupActiveTokenParams auth.LookupActiveTokenParams)) *MockStore_LookupActiveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.LookupActiveTokenParams
		if args[1] != nil {
			arg1 = args[1].(auth.LookupActiveTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_LookupActiveToken_Call) Return(token auth.Token, err error) *MockStore_LookupActiveToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockStore_LookupActiveToken_Call) RunAndReturn(run func(context1 context.Context, lookupActiveTokenParams auth.LookupActiveTokenParams) (auth.Token, error)) *MockStore_LookupActiveToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTokenUsed provides a mock function for the type MockStore
func (_mock *MockStore) MarkTokenUsed(context1 context.Context, markTokenUsedParams auth.MarkTokenUsedParams) (auth.Token, error) {
	ret := _mock.Called(context1, markTokenUsedParams)

	if len(ret) == 0 {
		panic("no return value specified for MarkTokenUsed")
	}

	var r0 auth.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.MarkTokenUsedParams) (auth.Token, error)); ok {
		return returnFunc(context1, markTokenUsedParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.MarkTokenUsedParams) auth.Token); ok {
		r0 = returnFunc(context1, markTokenUsedParams)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.MarkTokenUsedParams) error); ok {
		r1 = returnFunc(context1, markTokenUsedParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MarkTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTokenUsed'
type MockStore_MarkTokenUsed_Call struct {
	*mock.Call
}

// MarkTokenUsed is a helper method to define mock.On call
//   - context1 context.Context
//   - markTokenUsedParams auth.MarkTokenUsedParams
func (_e *MockStore_Expecter) MarkTokenUsed(context1 interface{}, markTokenUsedParams interface{}) *MockStore_MarkTokenUsed_Call {
	return &MockStore_MarkTokenUsed_Call{Call: _e.mock.On("MarkTokenUsed", context1, markTokenUsedParams)}
}

func (_c *MockStore_MarkTokenUsed_Call) Run(run func(context1 context.Context, markTokenUsedParams auth.MarkTokenUsedParams)) *MockStore_MarkTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.MarkTokenUsedParams
		if args[1] != nil {
			arg1 = args[1].(auth.MarkTokenUsedParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_MarkTokenUsed_Call) Return(token auth.Token, err error) *MockStore_MarkTokenUsed_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockStore_MarkTokenUsed_Call) RunAndReturn(run func(context1 context.Context, markTokenUsedParams auth.MarkTokenUsedParams) (auth.Token, error)) *MockStore_MarkTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockStore
func (_mock *MockStore) RevokeToken(context1 context.Context, revokeTokenParams auth.RevokeTokenParams) (auth.Token, error) {
	ret := _mock.Called(context1, revokeTokenParams)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 auth.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RevokeTokenParams) (auth.Token, error)); ok {
		return returnFunc(context1, revokeTokenParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RevokeTokenParams) auth.Token); ok {
		r0 = returnFunc(context1, revokeTokenParams)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RevokeTokenParams) error); ok {
		r1 = returnFunc(context1, revokeTokenParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockStore_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - context1 context.Context
//   - revokeTokenParams auth.RevokeTokenParams
func (_e *MockStore_Expecter) RevokeToken(context1 interface{}, revokeTokenParams interface{}) *MockStore_RevokeToken_Call {
	return &MockStore_RevokeToken_Call{Call: _e.mock.On("RevokeToken", context1, revokeTokenParams)}
}

func (_c *MockStore_RevokeToken_Call) Run(run func(context1 context.Context, revokeTokenParams auth.RevokeTokenParams)) *MockStore_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RevokeTokenParams
		if args[1] != nil {
			arg1 = args[1].(auth.RevokeTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_RevokeToken_Call) Return(token auth.Token, err error) *MockStore_RevokeToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockStore_RevokeToken_Call) RunAndReturn(run func(context1 context.Context, revokeTokenParams auth.RevokeTokenParams) (auth.Token, error)) *MockStore_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}
