// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/catalog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AddArtifact provides a mock function for the type MockStore
func (_mock *MockStore) AddArtifact(context1 context.Context, addArtifactParams catalog.AddArtifactParams) (catalog.Artifact, error) {
	ret := _mock.Called(context1, addArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for AddArtifact")
	}

	var r0 catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddArtifactParams) (catalog.Artifact, error)); ok {
		return returnFunc(context1, addArtifactParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddArtifactParams) catalog.Artifact); ok {
		r0 = returnFunc(context1, addArtifactParams)
	} else {
		r0 = ret.Get(0).(catalog.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.AddArtifactParams) error); ok {
		r1 = returnFunc(context1, addArtifactParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AddArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddArtifact'
type MockStore_AddArtifact_Call struct {
	*mock.Call
}

// AddArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - addArtifactParams catalog.AddArtifactParams
func (_e *MockStore_Expecter) AddArtifact(context1 interface{}, addArtifactParams interface{}) *MockStore_AddArtifact_Call {
	return &MockStore_AddArtifact_Call{Call: _e.mock.On("AddArtifact", context1, addArtifactParams)}
}

func (_c *MockStore_AddArtifact_Call) Run(run func(context1 context.Context, addArtifactParams catalog.AddArtifactParams)) *MockStore_AddArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.AddArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.AddArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AddArtifact_Call) Return(artifact catalog.Artifact, err error) *MockStore_AddArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockStore_AddArtifact_Call) RunAndReturn(run func(context1 context.Context, addArtifactParams catalog.AddArtifactParams) (catalog.Artifact, error)) *MockStore_AddArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// AddAttachment provides a mock function for the type MockStore
func (_mock *MockStore) AddAttachment(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams) (catalog.Attachment, error) {
	ret := _mock.Called(context1, addAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for AddAttachment")
	}

	var r0 catalog.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddAttachmentParams) (catalog.Attachment, error)); ok {
		return returnFunc(context1, addAttachmentParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddAttachmentParams) catalog.Attachment); ok {
		r0 = returnFunc(context1, addAttachmentParams)
	} else {
		r0 = ret.Get(0).(catalog.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.AddAttachmentParams) error); ok {
		r1 = returnFunc(context1, addAttachmentParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AddAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAttachment'
type MockStore_AddAttachment_Call struct {
	*mock.Call
}

// AddAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - addAttachmentParams catalog.AddAttachmentParams
func (_e *MockStore_Expecter) AddAttachment(context1 interface{}, addAttachmentParams interface{}) *MockStore_AddAttachment_Call {
	return &MockStore_AddAttachment_Call{Call: _e.mock.On("AddAttachment", context1, addAttachmentParams)}
}

func (_c *MockStore_AddAttachment_Call) Run(run func(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams)) *MockStore_AddAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.AddAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.AddAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AddAttachment_Call) Return(attachment catalog.Attachment, err error) *MockStore_AddAttachment_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockStore_AddAttachment_Call) RunAndReturn(run func(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams) (catalog.Attachment, error)) *MockStore_AddAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDraftVersion provides a mock function for the type MockStore
func (_mock *MockStore) CreateDraftVersion(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams) (catalog.Version, error) {
	ret := _mock.Called(context1, createDraftVersionParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftVersion")
	}

	var r0 catalog.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateDraftVersionParams) (catalog.Version, error)); ok {
		return returnFunc(context1, createDraftVersionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateDraftVersionParams) catalog.Version); ok {
		r0 = returnFunc(context1, createDraftVersionParams)
	} else {
		r0 = ret.Get(0).(catalog.Version)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.CreateDraftVersionParams) error); ok {
		r1 = returnFunc(context1, createDraftVersionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateDraftVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraftVersion'
type MockStore_CreateDraftVersion_Call struct {
	*mock.Call
}

// CreateDraftVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - createDraftVersionParams catalog.CreateDraftVersionParams
func (_e *MockStore_Expecter) CreateDraftVersion(context1 interface{}, createDraftVersionParams interface{}) *MockStore_CreateDraftVersion_Call {
	return &MockStore_CreateDraftVersion_Call{Call: _e.mock.On("CreateDraftVersion", context1, createDraftVersionParams)}
}

func (_c *MockStore_CreateDraftVersion_Call) Run(run func(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams)) *MockStore_CreateDraftVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.CreateDraftVersionParams
		if args[1] != nil {
			arg1 = args[1].(catalog.CreateDraftVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateDraftVersion_Call) Return(version catalog.Version, err error) *MockStore_CreateDraftVersion_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *MockStore_CreateDraftVersion_Call) RunAndReturn(run func(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams) (catalog.Version, error)) *MockStore_CreateDraftVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImage provides a mock function for the type MockStore
func (_mock *MockStore) CreateImage(context1 context.Context, createImageParams catalog.CreateImageParams) (catalog.Image, error) {
	ret := _mock.Called(context1, createImageParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateImageParams) (catalog.Image, error)); ok {
		return returnFunc(context1, createImageParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateImageParams) catalog.Image); ok {
		r0 = returnFunc(context1, createImageParams)
	} else {
		r0 = ret.Get(0).(catalog.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.CreateImageParams) error); ok {
		r1 = returnFunc(context1, createImageParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImage'
type MockStore_CreateImage_Call struct {
	*mock.Call
}

// CreateImage is a helper method to define mock.On call
//   - context1 context.Context
//   - createImageParams catalog.CreateImageParams
func (_e *MockStore_Expecter) CreateImage(context1 interface{}, createImageParams interface{}) *MockStore_CreateImage_Call {
	return &MockStore_CreateImage_Call{Call: _e.mock.On("CreateImage", context1, createImageParams)}
}

func (_c *MockStore_CreateImage_Call) Run(run func(context1 context.Context, createImageParams catalog.CreateImageParams)) *MockStore_CreateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.CreateImageParams
		if args[1] != nil {
			arg1 = args[1].(catalog.CreateImageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateImage_Call) Return(image catalog.Image, err error) *MockStore_CreateImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockStore_CreateImage_Call) RunAndReturn(run func(context1 context.Context, createImageParams catalog.CreateImageParams) (catalog.Image, error)) *MockStore_CreateImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlias provides a mock function for the type MockStore
func (_mock *MockStore) DeleteAlias(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams) error {
	ret := _mock.Called(context1, deleteAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlias")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteAliasParams) error); ok {
		r0 = returnFunc(context1, deleteAliasParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlias'
type MockStore_DeleteAlias_Call struct {
	*mock.Call
}

// DeleteAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteAliasParams catalog.DeleteAliasParams
func (_e *MockStore_Expecter) DeleteAlias(context1 interface{}, deleteAliasParams interface{}) *MockStore_DeleteAlias_Call {
	return &MockStore_DeleteAlias_Call{Call: _e.mock.On("DeleteAlias", context1, deleteAliasParams)}
}

func (_c *MockStore_DeleteAlias_Call) Run(run func(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams)) *MockStore_DeleteAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteAlias_Call) Return(err error) *MockStore_DeleteAlias_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteAlias_Call) RunAndReturn(run func(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams) error) *MockStore_DeleteAlias_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtifact provides a mock function for the type MockStore
func (_mock *MockStore) DeleteArtifact(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams) error {
	ret := _mock.Called(context1, deleteArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteArtifactParams) error); ok {
		r0 = returnFunc(context1, deleteArtifactParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type MockStore_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteArtifactParams catalog.DeleteArtifactParams
func (_e *MockStore_Expecter) DeleteArtifact(context1 interface{}, deleteArtifactParams interface{}) *MockStore_DeleteArtifact_Call {
	return &MockStore_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", context1, deleteArtifactParams)}
}

func (_c *MockStore_DeleteArtifact_Call) Run(run func(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams)) *MockStore_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteArtifact_Call) Return(err error) *MockStore_DeleteArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteArtifact_Call) RunAndReturn(run func(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams) error) *MockStore_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function for the type MockStore
func (_mock *MockStore) DeleteAttachment(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams) error {
	ret := _mock.Called(context1, deleteAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteAttachmentParams) error); ok {
		r0 = returnFunc(context1, deleteAttachmentParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockStore_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteAttachmentParams catalog.DeleteAttachmentParams
func (_e *MockStore_Expecter) DeleteAttachment(context1 interface{}, deleteAttachmentParams interface{}) *MockStore_DeleteAttachment_Call {
	return &MockStore_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", context1, deleteAttachmentParams)}
}

func (_c *MockStore_DeleteAttachment_Call) Run(run func(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams)) *MockStore_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteAttachment_Call) Return(err error) *MockStore_DeleteAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteAttachment_Call) RunAndReturn(run func(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams) error) *MockStore_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlias provides a mock function for the type MockStore
func (_mock *MockStore) GetAlias(context1 context.Context, getAliasParams catalog.GetAliasParams) (catalog.Alias, error) {
	ret := _mock.Called(context1, getAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for GetAlias")
	}

	var r0 catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetAliasParams) (catalog.Alias, error)); ok {
		return returnFunc(context1, getAliasParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetAliasParams) catalog.Alias); ok {
		r0 = returnFunc(context1, getAliasParams)
	} else {
		r0 = ret.Get(0).(catalog.Alias)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetAliasParams) error); ok {
		r1 = returnFunc(context1, getAliasParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlias'
type MockStore_GetAlias_Call struct {
	*mock.Call
}

// GetAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - getAliasParams catalog.GetAliasParams
func (_e *MockStore_Expecter) GetAlias(context1 interface{}, getAliasParams interface{}) *MockStore_GetAlias_Call {
	return &MockStore_GetAlias_Call{Call: _e.mock.On("GetAlias", context1, getAliasParams)}
}

func (_c *MockStore_GetAlias_Call) Run(run func(context1 context.Context, getAliasParams catalog.GetAliasParams)) *MockStore_GetAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetAlias_Call) Return(alias catalog.Alias, err error) *MockStore_GetAlias_Call {
	_c.Call.Return(alias, err)
	return _c
}

func (_c *MockStore_GetAlias_Call) RunAndReturn(run func(context1 context.Context, getAliasParams catalog.GetAliasParams) (catalog.Alias, error)) *MockStore_GetAlias_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type MockStore
func (_mock *MockStore) GetImage(context1 context.Context, getImageParams catalog.GetImageParams) (catalog.Image, error) {
	ret := _mock.Called(context1, getImageParams)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetImageParams) (catalog.Image, error)); ok {
		return returnFunc(context1, getImageParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetImageParams) catalog.Image); ok {
		r0 = returnFunc(context1, getImageParams)
	} else {
		r0 = ret.Get(0).(catalog.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetImageParams) error); ok {
		r1 = returnFunc(context1, getImageParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockStore_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - context1 context.Context
//   - getImageParams catalog.GetImageParams
func (_e *MockStore_Expecter) GetImage(context1 interface{}, getImageParams interface{}) *MockStore_GetImage_Call {
	return &MockStore_GetImage_Call{Call: _e.mock.On("GetImage", context1, getImageParams)}
}

func (_c *MockStore_GetImage_Call) Run(run func(context1 context.Context, getImageParams catalog.GetImageParams)) *MockStore_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetImageParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetImageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetImage_Call) Return(image catalog.Image, err error) *MockStore_GetImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockStore_GetImage_Call) RunAndReturn(run func(context1 context.Context, getImageParams catalog.GetImageParams) (catalog.Image, error)) *MockStore_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedArtifact provides a mock function for the type MockStore
func (_mock *MockStore) GetPublishedArtifact(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams) (catalog.Artifact, error) {
	ret := _mock.Called(context1, getPublishedArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedArtifact")
	}

	var r0 catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedArtifactParams) (catalog.Artifact, error)); ok {
		return returnFunc(context1, getPublishedArtifactParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedArtifactParams) catalog.Artifact); ok {
		r0 = returnFunc(context1, getPublishedArtifactParams)
	} else {
		r0 = ret.Get(0).(catalog.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetPublishedArtifactParams) error); ok {
		r1 = returnFunc(context1, getPublishedArtifactParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetPublishedArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedArtifact'
type MockStore_GetPublishedArtifact_Call struct {
	*mock.Call
}

// GetPublishedArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - getPublishedArtifactParams catalog.GetPublishedArtifactParams
func (_e *MockStore_Expecter) GetPublishedArtifact(context1 interface{}, getPublishedArtifactParams interface{}) *MockStore_GetPublishedArtifact_Call {
	return &MockStore_GetPublishedArtifact_Call{Call: _e.mock.On("GetPublishedArtifact", context1, getPublishedArtifactParams)}
}

func (_c *MockStore_GetPublishedArtifact_Call) Run(run func(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams)) *MockStore_GetPublishedArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetPublishedArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetPublishedArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetPublishedArtifact_Call) Return(artifact catalog.Artifact, err error) *MockStore_GetPublishedArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockStore_GetPublishedArtifact_Call) RunAndReturn(run func(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams) (catalog.Artifact, error)) *MockStore_GetPublishedArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedAttachment provides a mock function for the type MockStore
func (_mock *MockStore) GetPublishedAttachment(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams) (catalog.Attachment, error) {
	ret := _mock.Called(context1, getPublishedAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedAttachment")
	}

	var r0 catalog.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedAttachmentParams) (catalog.Attachment, error)); ok {
		return returnFunc(context1, getPublishedAttachmentParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedAttachmentParams) catalog.Attachment); ok {
		r0 = returnFunc(context1, getPublishedAttachmentParams)
	} else {
		r0 = ret.Get(0).(catalog.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetPublishedAttachmentParams) error); ok {
		r1 = returnFunc(context1, getPublishedAttachmentParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetPublishedAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedAttachment'
type MockStore_GetPublishedAttachment_Call struct {
	*mock.Call
}

// GetPublishedAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - getPublishedAttachmentParams catalog.GetPublishedAttachmentParams
func (_e *MockStore_Expecter) GetPublishedAttachment(context1 interface{}, getPublishedAttachmentParams interface{}) *MockStore_GetPublishedAttachment_Call {
	return &MockStore_GetPublishedAttachment_Call{Call: _e.mock.On("GetPublishedAttachment", context1, getPublishedAttachmentParams)}
}

func (_c *MockStore_GetPublishedAttachment_Call) Run(run func(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams)) *MockStore_GetPublishedAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetPublishedAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetPublishedAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetPublishedAttachment_Call) Return(attachment catalog.Attachment, err error) *MockStore_GetPublishedAttachment_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockStore_GetPublishedAttachment_Call) RunAndReturn(run func(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams) (catalog.Attachment, error)) *MockStore_GetPublishedAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionManifest provides a mock function for the type MockStore
func (_mock *MockStore) GetVersionManifest(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams) (catalog.Manifest, error) {
	ret := _mock.Called(context1, getVersionManifestParams)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionManifest")
	}

	var r0 catalog.Manifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetVersionManifestParams) (catalog.Manifest, error)); ok {
		return returnFunc(context1, getVersionManifestParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetVersionManifestParams) catalog.Manifest); ok {
		r0 = returnFunc(context1, getVersionManifestParams)
	} else {
		r0 = ret.Get(0).(catalog.Manifest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetVersionManifestParams) error); ok {
		r1 = returnFunc(context1, getVersionManifestParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetVersionManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionManifest'
type MockStore_GetVersionManifest_Call struct {
	*mock.Call
}

// GetVersionManifest is a helper method to define mock.On call
//   - context1 context.Context
//   - getVersionManifestParams catalog.GetVersionManifestParams
func (_e *MockStore_Expecter) GetVersionManifest(context1 interface{}, getVersionManifestParams interface{}) *MockStore_GetVersionManifest_Call {
	return &MockStore_GetVersionManifest_Call{Call: _e.mock.On("GetVersionManifest", context1, getVersionManifestParams)}
}

func (_c *MockStore_GetVersionManifest_Call) Run(run func(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams)) *MockStore_GetVersionManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetVersionManifestParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetVersionManifestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetVersionManifest_Call) Return(manifest catalog.Manifest, err error) *MockStore_GetVersionManifest_Call {
	_c.Call.Return(manifest, err)
	return _c
}

func (_c *MockStore_GetVersionManifest_Call) RunAndReturn(run func(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams) (catalog.Manifest, error)) *MockStore_GetVersionManifest_Call {
	_c.Call.Return(run)
	return _c
}

// ListAliases provides a mock function for the type MockStore
func (_mock *MockStore) ListAliases(context1 context.Context, listAliasesParams catalog.ListAliasesParams) ([]catalog.Alias, error) {
	ret := _mock.Called(context1, listAliasesParams)

	if len(ret) == 0 {
		panic("no return value specified for ListAliases")
	}

	var r0 []catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListAliasesParams) ([]catalog.Alias, error)); ok {
		return returnFunc(context1, listAliasesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListAliasesParams) []catalog.Alias); ok {
		r0 = returnFunc(context1, listAliasesParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Alias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListAliasesParams) error); ok {
		r1 = returnFunc(context1, listAliasesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAliases'
type MockStore_ListAliases_Call struct {
	*mock.Call
}

// ListAliases is a helper method to define mock.On call
//   - context1 context.Context
//   - listAliasesParams catalog.ListAliasesParams
func (_e *MockStore_Expecter) ListAliases(context1 interface{}, listAliasesParams interface{}) *MockStore_ListAliases_Call {
	return &MockStore_ListAliases_Call{Call: _e.mock.On("ListAliases", context1, listAliasesParams)}
}

func (_c *MockStore_ListAliases_Call) Run(run func(context1 context.Context, listAliasesParams catalog.ListAliasesParams)) *MockStore_ListAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListAliasesParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListAliasesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListAliases_Call) Return(aliass []catalog.Alias, err error) *MockStore_ListAliases_Call {
	_c.Call.Return(aliass, err)
	return _c
}

func (_c *MockStore_ListAliases_Call) RunAndReturn(run func(context1 context.Context, listAliasesParams catalog.ListAliasesParams) ([]catalog.Alias, error)) *MockStore_ListAliases_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockStore
func (_mock *MockStore) ListImages(context1 context.Context, listImagesParams catalog.ListImagesParams) ([]catalog.Image, error) {
	ret := _mock.Called(context1, listImagesParams)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListImagesParams) ([]catalog.Image, error)); ok {
		return returnFunc(context1, listImagesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListImagesParams) []catalog.Image); ok {
		r0 = returnFunc(context1, listImagesParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListImagesParams) error); ok {
		r1 = returnFunc(context1, listImagesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockStore_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - context1 context.Context
//   - listImagesParams catalog.ListImagesParams
func (_e *MockStore_Expecter) ListImages(context1 interface{}, listImagesParams interface{}) *MockStore_ListImages_Call {
	return &MockStore_ListImages_Call{Call: _e.mock.On("ListImages", context1, listImagesParams)}
}

func (_c *MockStore_ListImages_Call) Run(run func(context1 context.Context, listImagesParams catalog.ListImagesParams)) *MockStore_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListImagesParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListImagesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListImages_Call) Return(images []catalog.Image, err error) *MockStore_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockStore_ListImages_Call) RunAndReturn(run func(context1 context.Context, listImagesParams catalog.ListImagesParams) ([]catalog.Image, error)) *MockStore_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublishedArtifacts provides a mock function for the type MockStore
func (_mock *MockStore) ListPublishedArtifacts(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error) {
	ret := _mock.Called(context1, listPublishedArtifactsParams)

	if len(ret) == 0 {
		panic("no return value specified for ListPublishedArtifacts")
	}

	var r0 []catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error)); ok {
		return returnFunc(context1, listPublishedArtifactsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListPublishedArtifactsParams) []catalog.Artifact); ok {
		r0 = returnFunc(context1, listPublishedArtifactsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListPublishedArtifactsParams) error); ok {
		r1 = returnFunc(context1, listPublishedArtifactsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListPublishedArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublishedArtifacts'
type MockStore_ListPublishedArtifacts_Call struct {
	*mock.Call
}

// ListPublishedArtifacts is a helper method to define mock.On call
//   - context1 context.Context
//   - listPublishedArtifactsParams catalog.ListPublishedArtifactsParams
func (_e *MockStore_Expecter) ListPublishedArtifacts(context1 interface{}, listPublishedArtifactsParams interface{}) *MockStore_ListPublishedArtifacts_Call {
	return &MockStore_ListPublishedArtifacts_Call{Call: _e.mock.On("ListPublishedArtifacts", context1, listPublishedArtifactsParams)}
}

func (_c *MockStore_ListPublishedArtifacts_Call) Run(run func(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams)) *MockStore_ListPublishedArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListPublishedArtifactsParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListPublishedArtifactsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListPublishedArtifacts_Call) Return(artifacts []catalog.Artifact, err error) *MockStore_ListPublishedArtifacts_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockStore_ListPublishedArtifacts_Call) RunAndReturn(run func(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error)) *MockStore_ListPublishedArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function for the type MockStore
func (_mock *MockStore) ListVersions(context1 context.Context, listVersionsParams catalog.ListVersionsParams) ([]catalog.Version, error) {
	ret := _mock.Called(context1, listVersionsParams)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []catalog.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListVersionsParams) ([]catalog.Version, error)); ok {
		return returnFunc(context1, listVersionsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListVersionsParams) []catalog.Version); ok {
		r0 = returnFunc(context1, listVersionsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Version)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListVersionsParams) error); ok {
		r1 = returnFunc(context1, listVersionsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockStore_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - context1 context.Context
//   - listVersionsParams catalog.ListVersionsParams
func (_e *MockStore_Expecter) ListVersions(context1 interface{}, listVersionsParams interface{}) *MockStore_ListVersions_Call {
	return &MockStore_ListVersions_Call{Call: _e.mock.On("ListVersions", context1, listVersionsParams)}
}

func (_c *MockStore_ListVersions_Call) Run(run func(context1 context.Context, listVersionsParams catalog.ListVersionsParams)) *MockStore_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListVersionsParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListVersionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListVersions_Call) Return(versions []catalog.Version, err error) *MockStore_ListVersions_Call {
	_c.Call.Return(versions, err)
	return _c
}

func (_c *MockStore_ListVersions_Call) RunAndReturn(run func(context1 context.Context, listVersionsParams catalog.ListVersionsParams) ([]catalog.Version, error)) *MockStore_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// PutAlias provides a mock function for the type MockStore
func (_mock *MockStore) PutAlias(context1 context.Context, putAliasParams catalog.PutAliasParams) (catalog.Alias, error) {
	ret := _mock.Called(context1, putAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for PutAlias")
	}

	var r0 catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PutAliasParams) (catalog.Alias, error)); ok {
		return returnFunc(context1, putAliasParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PutAliasParams) catalog.Alias); ok {
		r0 = returnFunc(context1, putAliasParams)
	} else {
		r0 = ret.Get(0).(catalog.Alias)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.PutAliasParams) error); ok {
		r1 = returnFunc(context1, putAliasParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PutAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutAlias'
type MockStore_PutAlias_Call struct {
	*mock.Call
}

// PutAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - putAliasParams catalog.PutAliasParams
func (_e *MockStore_Expecter) PutAlias(context1 interface{}, putAliasParams interface{}) *MockStore_PutAlias_Call {
	return &MockStore_PutAlias_Call{Call: _e.mock.On("PutAlias", context1, putAliasParams)}
}

func (_c *MockStore_PutAlias_Call) Run(run func(context1 context.Context, putAliasParams catalog.PutAliasParams)) *MockStore_PutAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.PutAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.PutAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutAlias_Call) Return(alias catalog.Alias, err error) *MockStore_PutAlias_Call {
	_c.Call.Return(alias, err)
	return _c
}

func (_c *MockStore_PutAlias_Call) RunAndReturn(run func(context1 context.Context, putAliasParams catalog.PutAliasParams) (catalog.Alias, error)) *MockStore_PutAlias_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveManifest provides a mock function for the type MockStore
func (_mock *MockStore) ResolveManifest(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams) (catalog.Manifest, error) {
	ret := _mock.Called(context1, resolveManifestParams)

	if len(ret) == 0 {
		panic("no return value specified for ResolveManifest")
	}

	var r0 catalog.Manifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ResolveManifestParams) (catalog.Manifest, error)); ok {
		return returnFunc(context1, resolveManifestParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ResolveManifestParams) catalog.Manifest); ok {
		r0 = returnFunc(context1, resolveManifestParams)
	} else {
		r0 = ret.Get(0).(catalog.Manifest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ResolveManifestParams) error); ok {
		r1 = returnFunc(context1, resolveManifestParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ResolveManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveManifest'
type MockStore_ResolveManifest_Call struct {
	*mock.Call
}

// ResolveManifest is a helper method to define mock.On call
//   - context1 context.Context
//   - resolveManifestParams catalog.ResolveManifestParams
func (_e *MockStore_Expecter) ResolveManifest(context1 interface{}, resolveManifestParams interface{}) *MockStore_ResolveManifest_Call {
	return &MockStore_ResolveManifest_Call{Call: _e.mock.On("ResolveManifest", context1, resolveManifestParams)}
}

func (_c *MockStore_ResolveManifest_Call) Run(run func(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams)) *MockStore_ResolveManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ResolveManifestParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ResolveManifestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ResolveManifest_Call) Return(manifest catalog.Manifest, err error) *MockStore_ResolveManifest_Call {
	_c.Call.Return(manifest, err)
	return _c
}

func (_c *MockStore_ResolveManifest_Call) RunAndReturn(run func(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams) (catalog.Manifest, error)) *MockStore_ResolveManifest_Call {
	_c.Call.Return(run)
	return _c
}
