// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/cas"
	"github.com/meigma/imgsrv/internal/uploads"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// FailIngestJob provides a mock function for the type MockStore
func (_mock *MockStore) FailIngestJob(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams) (uploads.IngestJob, error) {
	ret := _mock.Called(context1, failIngestJobParams)

	if len(ret) == 0 {
		panic("no return value specified for FailIngestJob")
	}

	var r0 uploads.IngestJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.FailIngestJobParams) (uploads.IngestJob, error)); ok {
		return returnFunc(context1, failIngestJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.FailIngestJobParams) uploads.IngestJob); ok {
		r0 = returnFunc(context1, failIngestJobParams)
	} else {
		r0 = ret.Get(0).(uploads.IngestJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.FailIngestJobParams) error); ok {
		r1 = returnFunc(context1, failIngestJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_FailIngestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailIngestJob'
type MockStore_FailIngestJob_Call struct {
	*mock.Call
}

// FailIngestJob is a helper method to define mock.On call
//   - context1 context.Context
//   - failIngestJobParams uploads.FailIngestJobParams
func (_e *MockStore_Expecter) FailIngestJob(context1 interface{}, failIngestJobParams interface{}) *MockStore_FailIngestJob_Call {
	return &MockStore_FailIngestJob_Call{Call: _e.mock.On("FailIngestJob", context1, failIngestJobParams)}
}

func (_c *MockStore_FailIngestJob_Call) Run(run func(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams)) *MockStore_FailIngestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.FailIngestJobParams
		if args[1] != nil {
			arg1 = args[1].(uploads.FailIngestJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_FailIngestJob_Call) Return(ingestJob uploads.IngestJob, err error) *MockStore_FailIngestJob_Call {
	_c.Call.Return(ingestJob, err)
	return _c
}

func (_c *MockStore_FailIngestJob_Call) RunAndReturn(run func(context1 context.Context, failIngestJobParams uploads.FailIngestJobParams) (uploads.IngestJob, error)) *MockStore_FailIngestJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type MockStore
func (_mock *MockStore) GetBlob(context1 context.Context, getBlobParams cas.GetBlobParams) (cas.Blob, error) {
	ret := _mock.Called(context1, getBlobParams)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 cas.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.GetBlobParams) (cas.Blob, error)); ok {
		return returnFunc(context1, getBlobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.GetBlobParams) cas.Blob); ok {
		r0 = returnFunc(context1, getBlobParams)
	} else {
		r0 = ret.Get(0).(cas.Blob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cas.GetBlobParams) error); ok {
		r1 = returnFunc(context1, getBlobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type MockStore_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - context1 context.Context
//   - getBlobParams cas.GetBlobParams
func (_e *MockStore_Expecter) GetBlob(context1 interface{}, getBlobParams interface{}) *MockStore_GetBlob_Call {
	return &MockStore_GetBlob_Call{Call: _e.mock.On("GetBlob", context1, getBlobParams)}
}

func (_c *MockStore_GetBlob_Call) Run(run func(context1 context.Context, getBlobParams cas.GetBlobParams)) *MockStore_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cas.GetBlobParams
		if args[1] != nil {
			arg1 = args[1].(cas.GetBlobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetBlob_Call) Return(blob cas.Blob, err error) *MockStore_GetBlob_Call {
	_c.Call.Return(blob, err)
	return _c
}

func (_c *MockStore_GetBlob_Call) RunAndReturn(run func(context1 context.Context, getBlobParams cas.GetBlobParams) (cas.Blob, error)) *MockStore_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// SucceedIngestJob provides a mock function for the type MockStore
func (_mock *MockStore) SucceedIngestJob(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams) (uploads.IngestJob, error) {
	ret := _mock.Called(context1, succeedIngestJobParams)

	if len(ret) == 0 {
		panic("no return value specified for SucceedIngestJob")
	}

	var r0 uploads.IngestJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.SucceedIngestJobParams) (uploads.IngestJob, error)); ok {
		return returnFunc(context1, succeedIngestJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.SucceedIngestJobParams) uploads.IngestJob); ok {
		r0 = returnFunc(context1, succeedIngestJobParams)
	} else {
		r0 = ret.Get(0).(uploads.IngestJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.SucceedIngestJobParams) error); ok {
		r1 = returnFunc(context1, succeedIngestJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SucceedIngestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SucceedIngestJob'
type MockStore_SucceedIngestJob_Call struct {
	*mock.Call
}

// SucceedIngestJob is a helper method to define mock.On call
//   - context1 context.Context
//   - succeedIngestJobParams uploads.SucceedIngestJobParams
func (_e *MockStore_Expecter) SucceedIngestJob(context1 interface{}, succeedIngestJobParams interface{}) *MockStore_SucceedIngestJob_Call {
	return &MockStore_SucceedIngestJob_Call{Call: _e.mock.On("SucceedIngestJob", context1, succeedIngestJobParams)}
}

func (_c *MockStore_SucceedIngestJob_Call) Run(run func(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams)) *MockStore_SucceedIngestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.SucceedIngestJobParams
		if args[1] != nil {
			arg1 = args[1].(uploads.SucceedIngestJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SucceedIngestJob_Call) Return(ingestJob uploads.IngestJob, err error) *MockStore_SucceedIngestJob_Call {
	_c.Call.Return(ingestJob, err)
	return _c
}

func (_c *MockStore_SucceedIngestJob_Call) RunAndReturn(run func(context1 context.Context, succeedIngestJobParams uploads.SucceedIngestJobParams) (uploads.IngestJob, error)) *MockStore_SucceedIngestJob_Call {
	_c.Call.Return(run)
	return _c
}
