// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/objectstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AbortMultipartUpload provides a mock function for the type MockStore
func (_mock *MockStore) AbortMultipartUpload(context1 context.Context, abortMultipartUploadParams objectstore.AbortMultipartUploadParams) error {
	ret := _mock.Called(context1, abortMultipartUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for AbortMultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.AbortMultipartUploadParams) error); ok {
		r0 = returnFunc(context1, abortMultipartUploadParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_AbortMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortMultipartUpload'
type MockStore_AbortMultipartUpload_Call struct {
	*mock.Call
}

// AbortMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - abortMultipartUploadParams objectstore.AbortMultipartUploadParams
func (_e *MockStore_Expecter) AbortMultipartUpload(context1 interface{}, abortMultipartUploadParams interface{}) *MockStore_AbortMultipartUpload_Call {
	return &MockStore_AbortMultipartUpload_Call{Call: _e.mock.On("AbortMultipartUpload", context1, abortMultipartUploadParams)}
}

func (_c *MockStore_AbortMultipartUpload_Call) Run(run func(context1 context.Context, abortMultipartUploadParams objectstore.AbortMultipartUploadParams)) *MockStore_AbortMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.AbortMultipartUploadParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.AbortMultipartUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AbortMultipartUpload_Call) Return(err error) *MockStore_AbortMultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_AbortMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, abortMultipartUploadParams objectstore.AbortMultipartUploadParams) error) *MockStore_AbortMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteMultipartUpload provides a mock function for the type MockStore
func (_mock *MockStore) CompleteMultipartUpload(context1 context.Context, completeMultipartUploadParams objectstore.CompleteMultipartUploadParams) (objectstore.ObjectInfo, error) {
	ret := _mock.Called(context1, completeMultipartUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 objectstore.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CompleteMultipartUploadParams) (objectstore.ObjectInfo, error)); ok {
		return returnFunc(context1, completeMultipartUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CompleteMultipartUploadParams) objectstore.ObjectInfo); ok {
		r0 = returnFunc(context1, completeMultipartUploadParams)
	} else {
		r0 = ret.Get(0).(objectstore.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.CompleteMultipartUploadParams) error); ok {
		r1 = returnFunc(context1, completeMultipartUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CompleteMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteMultipartUpload'
type MockStore_CompleteMultipartUpload_Call struct {
	*mock.Call
}

// CompleteMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - completeMultipartUploadParams objectstore.CompleteMultipartUploadParams
func (_e *MockStore_Expecter) CompleteMultipartUpload(context1 interface{}, completeMultipartUploadParams interface{}) *MockStore_CompleteMultipartUpload_Call {
	return &MockStore_CompleteMultipartUpload_Call{Call: _e.mock.On("CompleteMultipartUpload", context1, completeMultipartUploadParams)}
}

func (_c *MockStore_CompleteMultipartUpload_Call) Run(run func(context1 context.Context, completeMultipartUploadParams objectstore.CompleteMultipartUploadParams)) *MockStore_CompleteMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.CompleteMultipartUploadParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.CompleteMultipartUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CompleteMultipartUpload_Call) Return(objectInfo objectstore.ObjectInfo, err error) *MockStore_CompleteMultipartUpload_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockStore_CompleteMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, completeMultipartUploadParams objectstore.CompleteMultipartUploadParams) (objectstore.ObjectInfo, error)) *MockStore_CompleteMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CopyObject provides a mock function for the type MockStore
func (_mock *MockStore) CopyObject(context1 context.Context, copyObjectParams objectstore.CopyObjectParams) (objectstore.ObjectInfo, error) {
	ret := _mock.Called(context1, copyObjectParams)

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 objectstore.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CopyObjectParams) (objectstore.ObjectInfo, error)); ok {
		return returnFunc(context1, copyObjectParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CopyObjectParams) objectstore.ObjectInfo); ok {
		r0 = returnFunc(context1, copyObjectParams)
	} else {
		r0 = ret.Get(0).(objectstore.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.CopyObjectParams) error); ok {
		r1 = returnFunc(context1, copyObjectParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CopyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyObject'
type MockStore_CopyObject_Call struct {
	*mock.Call
}

// CopyObject is a helper method to define mock.On call
//   - context1 context.Context
//   - copyObjectParams objectstore.CopyObjectParams
func (_e *MockStore_Expecter) CopyObject(context1 interface{}, copyObjectParams interface{}) *MockStore_CopyObject_Call {
	return &MockStore_CopyObject_Call{Call: _e.mock.On("CopyObject", context1, copyObjectParams)}
}

func (_c *MockStore_CopyObject_Call) Run(run func(context1 context.Context, copyObjectParams objectstore.CopyObjectParams)) *MockStore_CopyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.CopyObjectParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.CopyObjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CopyObject_Call) Return(objectInfo objectstore.ObjectInfo, err error) *MockStore_CopyObject_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockStore_CopyObject_Call) RunAndReturn(run func(context1 context.Context, copyObjectParams objectstore.CopyObjectParams) (objectstore.ObjectInfo, error)) *MockStore_CopyObject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMultipartUpload provides a mock function for the type MockStore
func (_mock *MockStore) CreateMultipartUpload(context1 context.Context, createMultipartUploadParams objectstore.CreateMultipartUploadParams) (objectstore.MultipartUpload, error) {
	ret := _mock.Called(context1, createMultipartUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateMultipartUpload")
	}

	var r0 objectstore.MultipartUpload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CreateMultipartUploadParams) (objectstore.MultipartUpload, error)); ok {
		return returnFunc(context1, createMultipartUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.CreateMultipartUploadParams) objectstore.MultipartUpload); ok {
		r0 = returnFunc(context1, createMultipartUploadParams)
	} else {
		r0 = ret.Get(0).(objectstore.MultipartUpload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.CreateMultipartUploadParams) error); ok {
		r1 = returnFunc(context1, createMultipartUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMultipartUpload'
type MockStore_CreateMultipartUpload_Call struct {
	*mock.Call
}

// CreateMultipartUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - createMultipartUploadParams objectstore.CreateMultipartUploadParams
func (_e *MockStore_Expecter) CreateMultipartUpload(context1 interface{}, createMultipartUploadParams interface{}) *MockStore_CreateMultipartUpload_Call {
	return &MockStore_CreateMultipartUpload_Call{Call: _e.mock.On("CreateMultipartUpload", context1, createMultipartUploadParams)}
}

func (_c *MockStore_CreateMultipartUpload_Call) Run(run func(context1 context.Context, createMultipartUploadParams objectstore.CreateMultipartUploadParams)) *MockStore_CreateMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.CreateMultipartUploadParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.CreateMultipartUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateMultipartUpload_Call) Return(multipartUpload objectstore.MultipartUpload, err error) *MockStore_CreateMultipartUpload_Call {
	_c.Call.Return(multipartUpload, err)
	return _c
}

func (_c *MockStore_CreateMultipartUpload_Call) RunAndReturn(run func(context1 context.Context, createMultipartUploadParams objectstore.CreateMultipartUploadParams) (objectstore.MultipartUpload, error)) *MockStore_CreateMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockStore
func (_mock *MockStore) DeleteObject(context1 context.Context, deleteObjectParams objectstore.DeleteObjectParams) error {
	ret := _mock.Called(context1, deleteObjectParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.DeleteObjectParams) error); ok {
		r0 = returnFunc(context1, deleteObjectParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockStore_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteObjectParams objectstore.DeleteObjectParams
func (_e *MockStore_Expecter) DeleteObject(context1 interface{}, deleteObjectParams interface{}) *MockStore_DeleteObject_Call {
	return &MockStore_DeleteObject_Call{Call: _e.mock.On("DeleteObject", context1, deleteObjectParams)}
}

func (_c *MockStore_DeleteObject_Call) Run(run func(context1 context.Context, deleteObjectParams objectstore.DeleteObjectParams)) *MockStore_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.DeleteObjectParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.DeleteObjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteObject_Call) Return(err error) *MockStore_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteObject_Call) RunAndReturn(run func(context1 context.Context, deleteObjectParams objectstore.DeleteObjectParams) error) *MockStore_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// OpenObject provides a mock function for the type MockStore
func (_mock *MockStore) OpenObject(context1 context.Context, openObjectParams objectstore.OpenObjectParams) (objectstore.ObjectReader, error) {
	ret := _mock.Called(context1, openObjectParams)

	if len(ret) == 0 {
		panic("no return value specified for OpenObject")
	}

	var r0 objectstore.ObjectReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.OpenObjectParams) (objectstore.ObjectReader, error)); ok {
		return returnFunc(context1, openObjectParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.OpenObjectParams) objectstore.ObjectReader); ok {
		r0 = returnFunc(context1, openObjectParams)
	} else {
		r0 = ret.Get(0).(objectstore.ObjectReader)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.OpenObjectParams) error); ok {
		r1 = returnFunc(context1, openObjectParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_OpenObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenObject'
type MockStore_OpenObject_Call struct {
	*mock.Call
}

// OpenObject is a helper method to define mock.On call
//   - context1 context.Context
//   - openObjectParams objectstore.OpenObjectParams
func (_e *MockStore_Expecter) OpenObject(context1 interface{}, openObjectParams interface{}) *MockStore_OpenObject_Call {
	return &MockStore_OpenObject_Call{Call: _e.mock.On("OpenObject", context1, openObjectParams)}
}

func (_c *MockStore_OpenObject_Call) Run(run func(context1 context.Context, openObjectParams objectstore.OpenObjectParams)) *MockStore_OpenObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.OpenObjectParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.OpenObjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_OpenObject_Call) Return(objectReader objectstore.ObjectReader, err error) *MockStore_OpenObject_Call {
	_c.Call.Return(objectReader, err)
	return _c
}

func (_c *MockStore_OpenObject_Call) RunAndReturn(run func(context1 context.Context, openObjectParams objectstore.OpenObjectParams) (objectstore.ObjectReader, error)) *MockStore_OpenObject_Call {
	_c.Call.Return(run)
	return _c
}

// PutPart provides a mock function for the type MockStore
func (_mock *MockStore) PutPart(context1 context.Context, putPartParams objectstore.PutPartParams) (objectstore.Part, error) {
	ret := _mock.Called(context1, putPartParams)

	if len(ret) == 0 {
		panic("no return value specified for PutPart")
	}

	var r0 objectstore.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.PutPartParams) (objectstore.Part, error)); ok {
		return returnFunc(context1, putPartParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.PutPartParams) objectstore.Part); ok {
		r0 = returnFunc(context1, putPartParams)
	} else {
		r0 = ret.Get(0).(objectstore.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.PutPartParams) error); ok {
		r1 = returnFunc(context1, putPartParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PutPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPart'
type MockStore_PutPart_Call struct {
	*mock.Call
}

// PutPart is a helper method to define mock.On call
//   - context1 context.Context
//   - putPartParams objectstore.PutPartParams
func (_e *MockStore_Expecter) PutPart(context1 interface{}, putPartParams interface{}) *MockStore_PutPart_Call {
	return &MockStore_PutPart_Call{Call: _e.mock.On("PutPart", context1, putPartParams)}
}

func (_c *MockStore_PutPart_Call) Run(run func(context1 context.Context, putPartParams objectstore.PutPartParams)) *MockStore_PutPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.PutPartParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.PutPartParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutPart_Call) Return(part objectstore.Part, err error) *MockStore_PutPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockStore_PutPart_Call) RunAndReturn(run func(context1 context.Context, putPartParams objectstore.PutPartParams) (objectstore.Part, error)) *MockStore_PutPart_Call {
	_c.Call.Return(run)
	return _c
}

// StatObject provides a mock function for the type MockStore
func (_mock *MockStore) StatObject(context1 context.Context, statObjectParams objectstore.StatObjectParams) (objectstore.ObjectInfo, error) {
	ret := _mock.Called(context1, statObjectParams)

	if len(ret) == 0 {
		panic("no return value specified for StatObject")
	}

	var r0 objectstore.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.StatObjectParams) (objectstore.ObjectInfo, error)); ok {
		return returnFunc(context1, statObjectParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, objectstore.StatObjectParams) objectstore.ObjectInfo); ok {
		r0 = returnFunc(context1, statObjectParams)
	} else {
		r0 = ret.Get(0).(objectstore.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, objectstore.StatObjectParams) error); ok {
		r1 = returnFunc(context1, statObjectParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_StatObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatObject'
type MockStore_StatObject_Call struct {
	*mock.Call
}

// StatObject is a helper method to define mock.On call
//   - context1 context.Context
//   - statObjectParams objectstore.StatObjectParams
func (_e *MockStore_Expecter) StatObject(context1 interface{}, statObjectParams interface{}) *MockStore_StatObject_Call {
	return &MockStore_StatObject_Call{Call: _e.mock.On("StatObject", context1, statObjectParams)}
}

func (_c *MockStore_StatObject_Call) Run(run func(context1 context.Context, statObjectParams objectstore.StatObjectParams)) *MockStore_StatObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 objectstore.StatObjectParams
		if args[1] != nil {
			arg1 = args[1].(objectstore.StatObjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_StatObject_Call) Return(objectInfo objectstore.ObjectInfo, err error) *MockStore_StatObject_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockStore_StatObject_Call) RunAndReturn(run func(context1 context.Context, statObjectParams objectstore.StatObjectParams) (objectstore.ObjectInfo, error)) *MockStore_StatObject_Call {
	_c.Call.Return(run)
	return _c
}
