// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/uploads"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// AbortUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) AbortUpload(context1 context.Context, abortUploadParams uploads.AbortUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, abortUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for AbortUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, abortUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, abortUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.AbortUploadParams) error); ok {
		r1 = returnFunc(context1, abortUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_AbortUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortUpload'
type MockUploadService_AbortUpload_Call struct {
	*mock.Call
}

// AbortUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - abortUploadParams uploads.AbortUploadParams
func (_e *MockUploadService_Expecter) AbortUpload(context1 interface{}, abortUploadParams interface{}) *MockUploadService_AbortUpload_Call {
	return &MockUploadService_AbortUpload_Call{Call: _e.mock.On("AbortUpload", context1, abortUploadParams)}
}

func (_c *MockUploadService_AbortUpload_Call) Run(run func(context1 context.Context, abortUploadParams uploads.AbortUploadParams)) *MockUploadService_AbortUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.AbortUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.AbortUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_AbortUpload_Call) Return(session uploads.Session, err error) *MockUploadService_AbortUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_AbortUpload_Call) RunAndReturn(run func(context1 context.Context, abortUploadParams uploads.AbortUploadParams) (uploads.Session, error)) *MockUploadService_AbortUpload_Call {
	_c.Call.Return(run)
	return _c
}

// BeginUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) BeginUpload(context1 context.Context, beginUploadParams uploads.BeginUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, beginUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for BeginUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.BeginUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, beginUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.BeginUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, beginUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.BeginUploadParams) error); ok {
		r1 = returnFunc(context1, beginUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_BeginUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginUpload'
type MockUploadService_BeginUpload_Call struct {
	*mock.Call
}

// BeginUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - beginUploadParams uploads.BeginUploadParams
func (_e *MockUploadService_Expecter) BeginUpload(context1 interface{}, beginUploadParams interface{}) *MockUploadService_BeginUpload_Call {
	return &MockUploadService_BeginUpload_Call{Call: _e.mock.On("BeginUpload", context1, beginUploadParams)}
}

func (_c *MockUploadService_BeginUpload_Call) Run(run func(context1 context.Context, beginUploadParams uploads.BeginUploadParams)) *MockUploadService_BeginUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.BeginUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.BeginUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_BeginUpload_Call) Return(session uploads.Session, err error) *MockUploadService_BeginUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_BeginUpload_Call) RunAndReturn(run func(context1 context.Context, beginUploadParams uploads.BeginUploadParams) (uploads.Session, error)) *MockUploadService_BeginUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CompleteUpload(context1 context.Context, completeUploadParams uploads.CompleteUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, completeUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, completeUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, completeUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.CompleteUploadParams) error); ok {
		r1 = returnFunc(context1, completeUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type MockUploadService_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - completeUploadParams uploads.CompleteUploadParams
func (_e *MockUploadService_Expecter) CompleteUpload(context1 interface{}, completeUploadParams interface{}) *MockUploadService_CompleteUpload_Call {
	return &MockUploadService_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", context1, completeUploadParams)}
}

func (_c *MockUploadService_CompleteUpload_Call) Run(run func(context1 context.Context, completeUploadParams uploads.CompleteUploadParams)) *MockUploadService_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.CompleteUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.CompleteUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_CompleteUpload_Call) Return(session uploads.Session, err error) *MockUploadService_CompleteUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_CompleteUpload_Call) RunAndReturn(run func(context1 context.Context, completeUploadParams uploads.CompleteUploadParams) (uploads.Session, error)) *MockUploadService_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetUpload(context1 context.Context, getUploadParams uploads.GetUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, getUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for GetUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, getUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, getUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.GetUploadParams) error); ok {
		r1 = returnFunc(context1, getUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpload'
type MockUploadService_GetUpload_Call struct {
	*mock.Call
}

// GetUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - getUploadParams uploads.GetUploadParams
func (_e *MockUploadService_Expecter) GetUpload(context1 interface{}, getUploadParams interface{}) *MockUploadService_GetUpload_Call {
	return &MockUploadService_GetUpload_Call{Call: _e.mock.On("GetUpload", context1, getUploadParams)}
}

func (_c *MockUploadService_GetUpload_Call) Run(run func(context1 context.Context, getUploadParams uploads.GetUploadParams)) *MockUploadService_GetUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.GetUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.GetUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_GetUpload_Call) Return(session uploads.Session, err error) *MockUploadService_GetUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_GetUpload_Call) RunAndReturn(run func(context1 context.Context, getUploadParams uploads.GetUploadParams) (uploads.Session, error)) *MockUploadService_GetUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PutUploadPart provides a mock function for the type MockUploadService
func (_mock *MockUploadService) PutUploadPart(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams) (uploads.Part, error) {
	ret := _mock.Called(context1, putUploadPartParams)

	if len(ret) == 0 {
		panic("no return value specified for PutUploadPart")
	}

	var r0 uploads.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutUploadPartParams) (uploads.Part, error)); ok {
		return returnFunc(context1, putUploadPartParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutUploadPartParams) uploads.Part); ok {
		r0 = returnFunc(context1, putUploadPartParams)
	} else {
		r0 = ret.Get(0).(uploads.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.PutUploadPartParams) error); ok {
		r1 = returnFunc(context1, putUploadPartParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_PutUploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutUploadPart'
type MockUploadService_PutUploadPart_Call struct {
	*mock.Call
}

// PutUploadPart is a helper method to define mock.On call
//   - context1 context.Context
//   - putUploadPartParams uploads.PutUploadPartParams
func (_e *MockUploadService_Expecter) PutUploadPart(context1 interface{}, putUploadPartParams interface{}) *MockUploadService_PutUploadPart_Call {
	return &MockUploadService_PutUploadPart_Call{Call: _e.mock.On("PutUploadPart", context1, putUploadPartParams)}
}

func (_c *MockUploadService_PutUploadPart_Call) Run(run func(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams)) *MockUploadService_PutUploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.PutUploadPartParams
		if args[1] != nil {
			arg1 = args[1].(uploads.PutUploadPartParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_PutUploadPart_Call) Return(part uploads.Part, err error) *MockUploadService_PutUploadPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockUploadService_PutUploadPart_Call) RunAndReturn(run func(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams) (uploads.Part, error)) *MockUploadService_PutUploadPart_Call {
	_c.Call.Return(run)
	return _c
}
