// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/imgsrv/internal/cas"
	"github.com/meigma/imgsrv/internal/catalog"
	"github.com/meigma/imgsrv/internal/objectstore"
	"github.com/meigma/imgsrv/internal/uploads"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// AbortUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) AbortUpload(context1 context.Context, abortUploadParams uploads.AbortUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, abortUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for AbortUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, abortUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.AbortUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, abortUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.AbortUploadParams) error); ok {
		r1 = returnFunc(context1, abortUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_AbortUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortUpload'
type MockUploadService_AbortUpload_Call struct {
	*mock.Call
}

// AbortUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - abortUploadParams uploads.AbortUploadParams
func (_e *MockUploadService_Expecter) AbortUpload(context1 interface{}, abortUploadParams interface{}) *MockUploadService_AbortUpload_Call {
	return &MockUploadService_AbortUpload_Call{Call: _e.mock.On("AbortUpload", context1, abortUploadParams)}
}

func (_c *MockUploadService_AbortUpload_Call) Run(run func(context1 context.Context, abortUploadParams uploads.AbortUploadParams)) *MockUploadService_AbortUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.AbortUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.AbortUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_AbortUpload_Call) Return(session uploads.Session, err error) *MockUploadService_AbortUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_AbortUpload_Call) RunAndReturn(run func(context1 context.Context, abortUploadParams uploads.AbortUploadParams) (uploads.Session, error)) *MockUploadService_AbortUpload_Call {
	_c.Call.Return(run)
	return _c
}

// BeginUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) BeginUpload(context1 context.Context, beginUploadParams uploads.BeginUploadParams) (uploads.BeginUploadResult, error) {
	ret := _mock.Called(context1, beginUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for BeginUpload")
	}

	var r0 uploads.BeginUploadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.BeginUploadParams) (uploads.BeginUploadResult, error)); ok {
		return returnFunc(context1, beginUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.BeginUploadParams) uploads.BeginUploadResult); ok {
		r0 = returnFunc(context1, beginUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.BeginUploadResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.BeginUploadParams) error); ok {
		r1 = returnFunc(context1, beginUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_BeginUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginUpload'
type MockUploadService_BeginUpload_Call struct {
	*mock.Call
}

// BeginUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - beginUploadParams uploads.BeginUploadParams
func (_e *MockUploadService_Expecter) BeginUpload(context1 interface{}, beginUploadParams interface{}) *MockUploadService_BeginUpload_Call {
	return &MockUploadService_BeginUpload_Call{Call: _e.mock.On("BeginUpload", context1, beginUploadParams)}
}

func (_c *MockUploadService_BeginUpload_Call) Run(run func(context1 context.Context, beginUploadParams uploads.BeginUploadParams)) *MockUploadService_BeginUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.BeginUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.BeginUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_BeginUpload_Call) Return(beginUploadResult uploads.BeginUploadResult, err error) *MockUploadService_BeginUpload_Call {
	_c.Call.Return(beginUploadResult, err)
	return _c
}

func (_c *MockUploadService_BeginUpload_Call) RunAndReturn(run func(context1 context.Context, beginUploadParams uploads.BeginUploadParams) (uploads.BeginUploadResult, error)) *MockUploadService_BeginUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CompleteUpload(context1 context.Context, completeUploadParams uploads.CompleteUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, completeUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, completeUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.CompleteUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, completeUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.CompleteUploadParams) error); ok {
		r1 = returnFunc(context1, completeUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type MockUploadService_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - completeUploadParams uploads.CompleteUploadParams
func (_e *MockUploadService_Expecter) CompleteUpload(context1 interface{}, completeUploadParams interface{}) *MockUploadService_CompleteUpload_Call {
	return &MockUploadService_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", context1, completeUploadParams)}
}

func (_c *MockUploadService_CompleteUpload_Call) Run(run func(context1 context.Context, completeUploadParams uploads.CompleteUploadParams)) *MockUploadService_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.CompleteUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.CompleteUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_CompleteUpload_Call) Return(session uploads.Session, err error) *MockUploadService_CompleteUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_CompleteUpload_Call) RunAndReturn(run func(context1 context.Context, completeUploadParams uploads.CompleteUploadParams) (uploads.Session, error)) *MockUploadService_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetUpload(context1 context.Context, getUploadParams uploads.GetUploadParams) (uploads.Session, error) {
	ret := _mock.Called(context1, getUploadParams)

	if len(ret) == 0 {
		panic("no return value specified for GetUpload")
	}

	var r0 uploads.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetUploadParams) (uploads.Session, error)); ok {
		return returnFunc(context1, getUploadParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.GetUploadParams) uploads.Session); ok {
		r0 = returnFunc(context1, getUploadParams)
	} else {
		r0 = ret.Get(0).(uploads.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.GetUploadParams) error); ok {
		r1 = returnFunc(context1, getUploadParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpload'
type MockUploadService_GetUpload_Call struct {
	*mock.Call
}

// GetUpload is a helper method to define mock.On call
//   - context1 context.Context
//   - getUploadParams uploads.GetUploadParams
func (_e *MockUploadService_Expecter) GetUpload(context1 interface{}, getUploadParams interface{}) *MockUploadService_GetUpload_Call {
	return &MockUploadService_GetUpload_Call{Call: _e.mock.On("GetUpload", context1, getUploadParams)}
}

func (_c *MockUploadService_GetUpload_Call) Run(run func(context1 context.Context, getUploadParams uploads.GetUploadParams)) *MockUploadService_GetUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.GetUploadParams
		if args[1] != nil {
			arg1 = args[1].(uploads.GetUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_GetUpload_Call) Return(session uploads.Session, err error) *MockUploadService_GetUpload_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUploadService_GetUpload_Call) RunAndReturn(run func(context1 context.Context, getUploadParams uploads.GetUploadParams) (uploads.Session, error)) *MockUploadService_GetUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PutUploadPart provides a mock function for the type MockUploadService
func (_mock *MockUploadService) PutUploadPart(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams) (uploads.Part, error) {
	ret := _mock.Called(context1, putUploadPartParams)

	if len(ret) == 0 {
		panic("no return value specified for PutUploadPart")
	}

	var r0 uploads.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutUploadPartParams) (uploads.Part, error)); ok {
		return returnFunc(context1, putUploadPartParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uploads.PutUploadPartParams) uploads.Part); ok {
		r0 = returnFunc(context1, putUploadPartParams)
	} else {
		r0 = ret.Get(0).(uploads.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uploads.PutUploadPartParams) error); ok {
		r1 = returnFunc(context1, putUploadPartParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_PutUploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutUploadPart'
type MockUploadService_PutUploadPart_Call struct {
	*mock.Call
}

// PutUploadPart is a helper method to define mock.On call
//   - context1 context.Context
//   - putUploadPartParams uploads.PutUploadPartParams
func (_e *MockUploadService_Expecter) PutUploadPart(context1 interface{}, putUploadPartParams interface{}) *MockUploadService_PutUploadPart_Call {
	return &MockUploadService_PutUploadPart_Call{Call: _e.mock.On("PutUploadPart", context1, putUploadPartParams)}
}

func (_c *MockUploadService_PutUploadPart_Call) Run(run func(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams)) *MockUploadService_PutUploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uploads.PutUploadPartParams
		if args[1] != nil {
			arg1 = args[1].(uploads.PutUploadPartParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_PutUploadPart_Call) Return(part uploads.Part, err error) *MockUploadService_PutUploadPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockUploadService_PutUploadPart_Call) RunAndReturn(run func(context1 context.Context, putUploadPartParams uploads.PutUploadPartParams) (uploads.Part, error)) *MockUploadService_PutUploadPart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogService creates a new instance of MockCatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogService {
	mock := &MockCatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogService is an autogenerated mock type for the CatalogService type
type MockCatalogService struct {
	mock.Mock
}

type MockCatalogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogService) EXPECT() *MockCatalogService_Expecter {
	return &MockCatalogService_Expecter{mock: &_m.Mock}
}

// AddArtifact provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) AddArtifact(context1 context.Context, addArtifactParams catalog.AddArtifactParams) (catalog.Artifact, error) {
	ret := _mock.Called(context1, addArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for AddArtifact")
	}

	var r0 catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddArtifactParams) (catalog.Artifact, error)); ok {
		return returnFunc(context1, addArtifactParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddArtifactParams) catalog.Artifact); ok {
		r0 = returnFunc(context1, addArtifactParams)
	} else {
		r0 = ret.Get(0).(catalog.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.AddArtifactParams) error); ok {
		r1 = returnFunc(context1, addArtifactParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_AddArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddArtifact'
type MockCatalogService_AddArtifact_Call struct {
	*mock.Call
}

// AddArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - addArtifactParams catalog.AddArtifactParams
func (_e *MockCatalogService_Expecter) AddArtifact(context1 interface{}, addArtifactParams interface{}) *MockCatalogService_AddArtifact_Call {
	return &MockCatalogService_AddArtifact_Call{Call: _e.mock.On("AddArtifact", context1, addArtifactParams)}
}

func (_c *MockCatalogService_AddArtifact_Call) Run(run func(context1 context.Context, addArtifactParams catalog.AddArtifactParams)) *MockCatalogService_AddArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.AddArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.AddArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_AddArtifact_Call) Return(artifact catalog.Artifact, err error) *MockCatalogService_AddArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockCatalogService_AddArtifact_Call) RunAndReturn(run func(context1 context.Context, addArtifactParams catalog.AddArtifactParams) (catalog.Artifact, error)) *MockCatalogService_AddArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// AddAttachment provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) AddAttachment(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams) (catalog.Attachment, error) {
	ret := _mock.Called(context1, addAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for AddAttachment")
	}

	var r0 catalog.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddAttachmentParams) (catalog.Attachment, error)); ok {
		return returnFunc(context1, addAttachmentParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.AddAttachmentParams) catalog.Attachment); ok {
		r0 = returnFunc(context1, addAttachmentParams)
	} else {
		r0 = ret.Get(0).(catalog.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.AddAttachmentParams) error); ok {
		r1 = returnFunc(context1, addAttachmentParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_AddAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAttachment'
type MockCatalogService_AddAttachment_Call struct {
	*mock.Call
}

// AddAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - addAttachmentParams catalog.AddAttachmentParams
func (_e *MockCatalogService_Expecter) AddAttachment(context1 interface{}, addAttachmentParams interface{}) *MockCatalogService_AddAttachment_Call {
	return &MockCatalogService_AddAttachment_Call{Call: _e.mock.On("AddAttachment", context1, addAttachmentParams)}
}

func (_c *MockCatalogService_AddAttachment_Call) Run(run func(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams)) *MockCatalogService_AddAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.AddAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.AddAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_AddAttachment_Call) Return(attachment catalog.Attachment, err error) *MockCatalogService_AddAttachment_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockCatalogService_AddAttachment_Call) RunAndReturn(run func(context1 context.Context, addAttachmentParams catalog.AddAttachmentParams) (catalog.Attachment, error)) *MockCatalogService_AddAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDraftVersion provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) CreateDraftVersion(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams) (catalog.Version, error) {
	ret := _mock.Called(context1, createDraftVersionParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftVersion")
	}

	var r0 catalog.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateDraftVersionParams) (catalog.Version, error)); ok {
		return returnFunc(context1, createDraftVersionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateDraftVersionParams) catalog.Version); ok {
		r0 = returnFunc(context1, createDraftVersionParams)
	} else {
		r0 = ret.Get(0).(catalog.Version)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.CreateDraftVersionParams) error); ok {
		r1 = returnFunc(context1, createDraftVersionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_CreateDraftVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraftVersion'
type MockCatalogService_CreateDraftVersion_Call struct {
	*mock.Call
}

// CreateDraftVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - createDraftVersionParams catalog.CreateDraftVersionParams
func (_e *MockCatalogService_Expecter) CreateDraftVersion(context1 interface{}, createDraftVersionParams interface{}) *MockCatalogService_CreateDraftVersion_Call {
	return &MockCatalogService_CreateDraftVersion_Call{Call: _e.mock.On("CreateDraftVersion", context1, createDraftVersionParams)}
}

func (_c *MockCatalogService_CreateDraftVersion_Call) Run(run func(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams)) *MockCatalogService_CreateDraftVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.CreateDraftVersionParams
		if args[1] != nil {
			arg1 = args[1].(catalog.CreateDraftVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_CreateDraftVersion_Call) Return(version catalog.Version, err error) *MockCatalogService_CreateDraftVersion_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *MockCatalogService_CreateDraftVersion_Call) RunAndReturn(run func(context1 context.Context, createDraftVersionParams catalog.CreateDraftVersionParams) (catalog.Version, error)) *MockCatalogService_CreateDraftVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImage provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) CreateImage(context1 context.Context, createImageParams catalog.CreateImageParams) (catalog.Image, error) {
	ret := _mock.Called(context1, createImageParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateImageParams) (catalog.Image, error)); ok {
		return returnFunc(context1, createImageParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.CreateImageParams) catalog.Image); ok {
		r0 = returnFunc(context1, createImageParams)
	} else {
		r0 = ret.Get(0).(catalog.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.CreateImageParams) error); ok {
		r1 = returnFunc(context1, createImageParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_CreateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImage'
type MockCatalogService_CreateImage_Call struct {
	*mock.Call
}

// CreateImage is a helper method to define mock.On call
//   - context1 context.Context
//   - createImageParams catalog.CreateImageParams
func (_e *MockCatalogService_Expecter) CreateImage(context1 interface{}, createImageParams interface{}) *MockCatalogService_CreateImage_Call {
	return &MockCatalogService_CreateImage_Call{Call: _e.mock.On("CreateImage", context1, createImageParams)}
}

func (_c *MockCatalogService_CreateImage_Call) Run(run func(context1 context.Context, createImageParams catalog.CreateImageParams)) *MockCatalogService_CreateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.CreateImageParams
		if args[1] != nil {
			arg1 = args[1].(catalog.CreateImageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_CreateImage_Call) Return(image catalog.Image, err error) *MockCatalogService_CreateImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockCatalogService_CreateImage_Call) RunAndReturn(run func(context1 context.Context, createImageParams catalog.CreateImageParams) (catalog.Image, error)) *MockCatalogService_CreateImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlias provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) DeleteAlias(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams) error {
	ret := _mock.Called(context1, deleteAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlias")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteAliasParams) error); ok {
		r0 = returnFunc(context1, deleteAliasParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogService_DeleteAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlias'
type MockCatalogService_DeleteAlias_Call struct {
	*mock.Call
}

// DeleteAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteAliasParams catalog.DeleteAliasParams
func (_e *MockCatalogService_Expecter) DeleteAlias(context1 interface{}, deleteAliasParams interface{}) *MockCatalogService_DeleteAlias_Call {
	return &MockCatalogService_DeleteAlias_Call{Call: _e.mock.On("DeleteAlias", context1, deleteAliasParams)}
}

func (_c *MockCatalogService_DeleteAlias_Call) Run(run func(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams)) *MockCatalogService_DeleteAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_DeleteAlias_Call) Return(err error) *MockCatalogService_DeleteAlias_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogService_DeleteAlias_Call) RunAndReturn(run func(context1 context.Context, deleteAliasParams catalog.DeleteAliasParams) error) *MockCatalogService_DeleteAlias_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtifact provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) DeleteArtifact(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams) error {
	ret := _mock.Called(context1, deleteArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteArtifactParams) error); ok {
		r0 = returnFunc(context1, deleteArtifactParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogService_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type MockCatalogService_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteArtifactParams catalog.DeleteArtifactParams
func (_e *MockCatalogService_Expecter) DeleteArtifact(context1 interface{}, deleteArtifactParams interface{}) *MockCatalogService_DeleteArtifact_Call {
	return &MockCatalogService_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", context1, deleteArtifactParams)}
}

func (_c *MockCatalogService_DeleteArtifact_Call) Run(run func(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams)) *MockCatalogService_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_DeleteArtifact_Call) Return(err error) *MockCatalogService_DeleteArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogService_DeleteArtifact_Call) RunAndReturn(run func(context1 context.Context, deleteArtifactParams catalog.DeleteArtifactParams) error) *MockCatalogService_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) DeleteAttachment(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams) error {
	ret := _mock.Called(context1, deleteAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.DeleteAttachmentParams) error); ok {
		r0 = returnFunc(context1, deleteAttachmentParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatalogService_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockCatalogService_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteAttachmentParams catalog.DeleteAttachmentParams
func (_e *MockCatalogService_Expecter) DeleteAttachment(context1 interface{}, deleteAttachmentParams interface{}) *MockCatalogService_DeleteAttachment_Call {
	return &MockCatalogService_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", context1, deleteAttachmentParams)}
}

func (_c *MockCatalogService_DeleteAttachment_Call) Run(run func(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams)) *MockCatalogService_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.DeleteAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.DeleteAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_DeleteAttachment_Call) Return(err error) *MockCatalogService_DeleteAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatalogService_DeleteAttachment_Call) RunAndReturn(run func(context1 context.Context, deleteAttachmentParams catalog.DeleteAttachmentParams) error) *MockCatalogService_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlias provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) GetAlias(context1 context.Context, getAliasParams catalog.GetAliasParams) (catalog.Alias, error) {
	ret := _mock.Called(context1, getAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for GetAlias")
	}

	var r0 catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetAliasParams) (catalog.Alias, error)); ok {
		return returnFunc(context1, getAliasParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetAliasParams) catalog.Alias); ok {
		r0 = returnFunc(context1, getAliasParams)
	} else {
		r0 = ret.Get(0).(catalog.Alias)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetAliasParams) error); ok {
		r1 = returnFunc(context1, getAliasParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_GetAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlias'
type MockCatalogService_GetAlias_Call struct {
	*mock.Call
}

// GetAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - getAliasParams catalog.GetAliasParams
func (_e *MockCatalogService_Expecter) GetAlias(context1 interface{}, getAliasParams interface{}) *MockCatalogService_GetAlias_Call {
	return &MockCatalogService_GetAlias_Call{Call: _e.mock.On("GetAlias", context1, getAliasParams)}
}

func (_c *MockCatalogService_GetAlias_Call) Run(run func(context1 context.Context, getAliasParams catalog.GetAliasParams)) *MockCatalogService_GetAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_GetAlias_Call) Return(alias catalog.Alias, err error) *MockCatalogService_GetAlias_Call {
	_c.Call.Return(alias, err)
	return _c
}

func (_c *MockCatalogService_GetAlias_Call) RunAndReturn(run func(context1 context.Context, getAliasParams catalog.GetAliasParams) (catalog.Alias, error)) *MockCatalogService_GetAlias_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) GetImage(context1 context.Context, getImageParams catalog.GetImageParams) (catalog.Image, error) {
	ret := _mock.Called(context1, getImageParams)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetImageParams) (catalog.Image, error)); ok {
		return returnFunc(context1, getImageParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetImageParams) catalog.Image); ok {
		r0 = returnFunc(context1, getImageParams)
	} else {
		r0 = ret.Get(0).(catalog.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetImageParams) error); ok {
		r1 = returnFunc(context1, getImageParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockCatalogService_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - context1 context.Context
//   - getImageParams catalog.GetImageParams
func (_e *MockCatalogService_Expecter) GetImage(context1 interface{}, getImageParams interface{}) *MockCatalogService_GetImage_Call {
	return &MockCatalogService_GetImage_Call{Call: _e.mock.On("GetImage", context1, getImageParams)}
}

func (_c *MockCatalogService_GetImage_Call) Run(run func(context1 context.Context, getImageParams catalog.GetImageParams)) *MockCatalogService_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetImageParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetImageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_GetImage_Call) Return(image catalog.Image, err error) *MockCatalogService_GetImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockCatalogService_GetImage_Call) RunAndReturn(run func(context1 context.Context, getImageParams catalog.GetImageParams) (catalog.Image, error)) *MockCatalogService_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedArtifact provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) GetPublishedArtifact(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams) (catalog.Artifact, error) {
	ret := _mock.Called(context1, getPublishedArtifactParams)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedArtifact")
	}

	var r0 catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedArtifactParams) (catalog.Artifact, error)); ok {
		return returnFunc(context1, getPublishedArtifactParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedArtifactParams) catalog.Artifact); ok {
		r0 = returnFunc(context1, getPublishedArtifactParams)
	} else {
		r0 = ret.Get(0).(catalog.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetPublishedArtifactParams) error); ok {
		r1 = returnFunc(context1, getPublishedArtifactParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_GetPublishedArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedArtifact'
type MockCatalogService_GetPublishedArtifact_Call struct {
	*mock.Call
}

// GetPublishedArtifact is a helper method to define mock.On call
//   - context1 context.Context
//   - getPublishedArtifactParams catalog.GetPublishedArtifactParams
func (_e *MockCatalogService_Expecter) GetPublishedArtifact(context1 interface{}, getPublishedArtifactParams interface{}) *MockCatalogService_GetPublishedArtifact_Call {
	return &MockCatalogService_GetPublishedArtifact_Call{Call: _e.mock.On("GetPublishedArtifact", context1, getPublishedArtifactParams)}
}

func (_c *MockCatalogService_GetPublishedArtifact_Call) Run(run func(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams)) *MockCatalogService_GetPublishedArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetPublishedArtifactParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetPublishedArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_GetPublishedArtifact_Call) Return(artifact catalog.Artifact, err error) *MockCatalogService_GetPublishedArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockCatalogService_GetPublishedArtifact_Call) RunAndReturn(run func(context1 context.Context, getPublishedArtifactParams catalog.GetPublishedArtifactParams) (catalog.Artifact, error)) *MockCatalogService_GetPublishedArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedAttachment provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) GetPublishedAttachment(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams) (catalog.Attachment, error) {
	ret := _mock.Called(context1, getPublishedAttachmentParams)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedAttachment")
	}

	var r0 catalog.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedAttachmentParams) (catalog.Attachment, error)); ok {
		return returnFunc(context1, getPublishedAttachmentParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetPublishedAttachmentParams) catalog.Attachment); ok {
		r0 = returnFunc(context1, getPublishedAttachmentParams)
	} else {
		r0 = ret.Get(0).(catalog.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetPublishedAttachmentParams) error); ok {
		r1 = returnFunc(context1, getPublishedAttachmentParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_GetPublishedAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedAttachment'
type MockCatalogService_GetPublishedAttachment_Call struct {
	*mock.Call
}

// GetPublishedAttachment is a helper method to define mock.On call
//   - context1 context.Context
//   - getPublishedAttachmentParams catalog.GetPublishedAttachmentParams
func (_e *MockCatalogService_Expecter) GetPublishedAttachment(context1 interface{}, getPublishedAttachmentParams interface{}) *MockCatalogService_GetPublishedAttachment_Call {
	return &MockCatalogService_GetPublishedAttachment_Call{Call: _e.mock.On("GetPublishedAttachment", context1, getPublishedAttachmentParams)}
}

func (_c *MockCatalogService_GetPublishedAttachment_Call) Run(run func(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams)) *MockCatalogService_GetPublishedAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetPublishedAttachmentParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetPublishedAttachmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_GetPublishedAttachment_Call) Return(attachment catalog.Attachment, err error) *MockCatalogService_GetPublishedAttachment_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockCatalogService_GetPublishedAttachment_Call) RunAndReturn(run func(context1 context.Context, getPublishedAttachmentParams catalog.GetPublishedAttachmentParams) (catalog.Attachment, error)) *MockCatalogService_GetPublishedAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionManifest provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) GetVersionManifest(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams) (catalog.Manifest, error) {
	ret := _mock.Called(context1, getVersionManifestParams)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionManifest")
	}

	var r0 catalog.Manifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetVersionManifestParams) (catalog.Manifest, error)); ok {
		return returnFunc(context1, getVersionManifestParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.GetVersionManifestParams) catalog.Manifest); ok {
		r0 = returnFunc(context1, getVersionManifestParams)
	} else {
		r0 = ret.Get(0).(catalog.Manifest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.GetVersionManifestParams) error); ok {
		r1 = returnFunc(context1, getVersionManifestParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_GetVersionManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionManifest'
type MockCatalogService_GetVersionManifest_Call struct {
	*mock.Call
}

// GetVersionManifest is a helper method to define mock.On call
//   - context1 context.Context
//   - getVersionManifestParams catalog.GetVersionManifestParams
func (_e *MockCatalogService_Expecter) GetVersionManifest(context1 interface{}, getVersionManifestParams interface{}) *MockCatalogService_GetVersionManifest_Call {
	return &MockCatalogService_GetVersionManifest_Call{Call: _e.mock.On("GetVersionManifest", context1, getVersionManifestParams)}
}

func (_c *MockCatalogService_GetVersionManifest_Call) Run(run func(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams)) *MockCatalogService_GetVersionManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.GetVersionManifestParams
		if args[1] != nil {
			arg1 = args[1].(catalog.GetVersionManifestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_GetVersionManifest_Call) Return(manifest catalog.Manifest, err error) *MockCatalogService_GetVersionManifest_Call {
	_c.Call.Return(manifest, err)
	return _c
}

func (_c *MockCatalogService_GetVersionManifest_Call) RunAndReturn(run func(context1 context.Context, getVersionManifestParams catalog.GetVersionManifestParams) (catalog.Manifest, error)) *MockCatalogService_GetVersionManifest_Call {
	_c.Call.Return(run)
	return _c
}

// ListAliases provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) ListAliases(context1 context.Context, listAliasesParams catalog.ListAliasesParams) ([]catalog.Alias, error) {
	ret := _mock.Called(context1, listAliasesParams)

	if len(ret) == 0 {
		panic("no return value specified for ListAliases")
	}

	var r0 []catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListAliasesParams) ([]catalog.Alias, error)); ok {
		return returnFunc(context1, listAliasesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListAliasesParams) []catalog.Alias); ok {
		r0 = returnFunc(context1, listAliasesParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Alias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListAliasesParams) error); ok {
		r1 = returnFunc(context1, listAliasesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_ListAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAliases'
type MockCatalogService_ListAliases_Call struct {
	*mock.Call
}

// ListAliases is a helper method to define mock.On call
//   - context1 context.Context
//   - listAliasesParams catalog.ListAliasesParams
func (_e *MockCatalogService_Expecter) ListAliases(context1 interface{}, listAliasesParams interface{}) *MockCatalogService_ListAliases_Call {
	return &MockCatalogService_ListAliases_Call{Call: _e.mock.On("ListAliases", context1, listAliasesParams)}
}

func (_c *MockCatalogService_ListAliases_Call) Run(run func(context1 context.Context, listAliasesParams catalog.ListAliasesParams)) *MockCatalogService_ListAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListAliasesParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListAliasesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_ListAliases_Call) Return(aliass []catalog.Alias, err error) *MockCatalogService_ListAliases_Call {
	_c.Call.Return(aliass, err)
	return _c
}

func (_c *MockCatalogService_ListAliases_Call) RunAndReturn(run func(context1 context.Context, listAliasesParams catalog.ListAliasesParams) ([]catalog.Alias, error)) *MockCatalogService_ListAliases_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) ListImages(context1 context.Context, listImagesParams catalog.ListImagesParams) ([]catalog.Image, error) {
	ret := _mock.Called(context1, listImagesParams)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []catalog.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListImagesParams) ([]catalog.Image, error)); ok {
		return returnFunc(context1, listImagesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListImagesParams) []catalog.Image); ok {
		r0 = returnFunc(context1, listImagesParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListImagesParams) error); ok {
		r1 = returnFunc(context1, listImagesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockCatalogService_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - context1 context.Context
//   - listImagesParams catalog.ListImagesParams
func (_e *MockCatalogService_Expecter) ListImages(context1 interface{}, listImagesParams interface{}) *MockCatalogService_ListImages_Call {
	return &MockCatalogService_ListImages_Call{Call: _e.mock.On("ListImages", context1, listImagesParams)}
}

func (_c *MockCatalogService_ListImages_Call) Run(run func(context1 context.Context, listImagesParams catalog.ListImagesParams)) *MockCatalogService_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListImagesParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListImagesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_ListImages_Call) Return(images []catalog.Image, err error) *MockCatalogService_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockCatalogService_ListImages_Call) RunAndReturn(run func(context1 context.Context, listImagesParams catalog.ListImagesParams) ([]catalog.Image, error)) *MockCatalogService_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublishedArtifacts provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) ListPublishedArtifacts(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error) {
	ret := _mock.Called(context1, listPublishedArtifactsParams)

	if len(ret) == 0 {
		panic("no return value specified for ListPublishedArtifacts")
	}

	var r0 []catalog.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error)); ok {
		return returnFunc(context1, listPublishedArtifactsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListPublishedArtifactsParams) []catalog.Artifact); ok {
		r0 = returnFunc(context1, listPublishedArtifactsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListPublishedArtifactsParams) error); ok {
		r1 = returnFunc(context1, listPublishedArtifactsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_ListPublishedArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublishedArtifacts'
type MockCatalogService_ListPublishedArtifacts_Call struct {
	*mock.Call
}

// ListPublishedArtifacts is a helper method to define mock.On call
//   - context1 context.Context
//   - listPublishedArtifactsParams catalog.ListPublishedArtifactsParams
func (_e *MockCatalogService_Expecter) ListPublishedArtifacts(context1 interface{}, listPublishedArtifactsParams interface{}) *MockCatalogService_ListPublishedArtifacts_Call {
	return &MockCatalogService_ListPublishedArtifacts_Call{Call: _e.mock.On("ListPublishedArtifacts", context1, listPublishedArtifactsParams)}
}

func (_c *MockCatalogService_ListPublishedArtifacts_Call) Run(run func(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams)) *MockCatalogService_ListPublishedArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListPublishedArtifactsParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListPublishedArtifactsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_ListPublishedArtifacts_Call) Return(artifacts []catalog.Artifact, err error) *MockCatalogService_ListPublishedArtifacts_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockCatalogService_ListPublishedArtifacts_Call) RunAndReturn(run func(context1 context.Context, listPublishedArtifactsParams catalog.ListPublishedArtifactsParams) ([]catalog.Artifact, error)) *MockCatalogService_ListPublishedArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) ListVersions(context1 context.Context, listVersionsParams catalog.ListVersionsParams) ([]catalog.Version, error) {
	ret := _mock.Called(context1, listVersionsParams)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []catalog.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListVersionsParams) ([]catalog.Version, error)); ok {
		return returnFunc(context1, listVersionsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ListVersionsParams) []catalog.Version); ok {
		r0 = returnFunc(context1, listVersionsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Version)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ListVersionsParams) error); ok {
		r1 = returnFunc(context1, listVersionsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockCatalogService_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - context1 context.Context
//   - listVersionsParams catalog.ListVersionsParams
func (_e *MockCatalogService_Expecter) ListVersions(context1 interface{}, listVersionsParams interface{}) *MockCatalogService_ListVersions_Call {
	return &MockCatalogService_ListVersions_Call{Call: _e.mock.On("ListVersions", context1, listVersionsParams)}
}

func (_c *MockCatalogService_ListVersions_Call) Run(run func(context1 context.Context, listVersionsParams catalog.ListVersionsParams)) *MockCatalogService_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ListVersionsParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ListVersionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_ListVersions_Call) Return(versions []catalog.Version, err error) *MockCatalogService_ListVersions_Call {
	_c.Call.Return(versions, err)
	return _c
}

func (_c *MockCatalogService_ListVersions_Call) RunAndReturn(run func(context1 context.Context, listVersionsParams catalog.ListVersionsParams) ([]catalog.Version, error)) *MockCatalogService_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// PublishVersion provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) PublishVersion(context1 context.Context, publishVersionParams catalog.PublishVersionParams) (catalog.Version, error) {
	ret := _mock.Called(context1, publishVersionParams)

	if len(ret) == 0 {
		panic("no return value specified for PublishVersion")
	}

	var r0 catalog.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PublishVersionParams) (catalog.Version, error)); ok {
		return returnFunc(context1, publishVersionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PublishVersionParams) catalog.Version); ok {
		r0 = returnFunc(context1, publishVersionParams)
	} else {
		r0 = ret.Get(0).(catalog.Version)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.PublishVersionParams) error); ok {
		r1 = returnFunc(context1, publishVersionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_PublishVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishVersion'
type MockCatalogService_PublishVersion_Call struct {
	*mock.Call
}

// PublishVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - publishVersionParams catalog.PublishVersionParams
func (_e *MockCatalogService_Expecter) PublishVersion(context1 interface{}, publishVersionParams interface{}) *MockCatalogService_PublishVersion_Call {
	return &MockCatalogService_PublishVersion_Call{Call: _e.mock.On("PublishVersion", context1, publishVersionParams)}
}

func (_c *MockCatalogService_PublishVersion_Call) Run(run func(context1 context.Context, publishVersionParams catalog.PublishVersionParams)) *MockCatalogService_PublishVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.PublishVersionParams
		if args[1] != nil {
			arg1 = args[1].(catalog.PublishVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_PublishVersion_Call) Return(version catalog.Version, err error) *MockCatalogService_PublishVersion_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *MockCatalogService_PublishVersion_Call) RunAndReturn(run func(context1 context.Context, publishVersionParams catalog.PublishVersionParams) (catalog.Version, error)) *MockCatalogService_PublishVersion_Call {
	_c.Call.Return(run)
	return _c
}

// PutAlias provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) PutAlias(context1 context.Context, putAliasParams catalog.PutAliasParams) (catalog.Alias, error) {
	ret := _mock.Called(context1, putAliasParams)

	if len(ret) == 0 {
		panic("no return value specified for PutAlias")
	}

	var r0 catalog.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PutAliasParams) (catalog.Alias, error)); ok {
		return returnFunc(context1, putAliasParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.PutAliasParams) catalog.Alias); ok {
		r0 = returnFunc(context1, putAliasParams)
	} else {
		r0 = ret.Get(0).(catalog.Alias)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.PutAliasParams) error); ok {
		r1 = returnFunc(context1, putAliasParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_PutAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutAlias'
type MockCatalogService_PutAlias_Call struct {
	*mock.Call
}

// PutAlias is a helper method to define mock.On call
//   - context1 context.Context
//   - putAliasParams catalog.PutAliasParams
func (_e *MockCatalogService_Expecter) PutAlias(context1 interface{}, putAliasParams interface{}) *MockCatalogService_PutAlias_Call {
	return &MockCatalogService_PutAlias_Call{Call: _e.mock.On("PutAlias", context1, putAliasParams)}
}

func (_c *MockCatalogService_PutAlias_Call) Run(run func(context1 context.Context, putAliasParams catalog.PutAliasParams)) *MockCatalogService_PutAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.PutAliasParams
		if args[1] != nil {
			arg1 = args[1].(catalog.PutAliasParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_PutAlias_Call) Return(alias catalog.Alias, err error) *MockCatalogService_PutAlias_Call {
	_c.Call.Return(alias, err)
	return _c
}

func (_c *MockCatalogService_PutAlias_Call) RunAndReturn(run func(context1 context.Context, putAliasParams catalog.PutAliasParams) (catalog.Alias, error)) *MockCatalogService_PutAlias_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveManifest provides a mock function for the type MockCatalogService
func (_mock *MockCatalogService) ResolveManifest(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams) (catalog.Manifest, error) {
	ret := _mock.Called(context1, resolveManifestParams)

	if len(ret) == 0 {
		panic("no return value specified for ResolveManifest")
	}

	var r0 catalog.Manifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ResolveManifestParams) (catalog.Manifest, error)); ok {
		return returnFunc(context1, resolveManifestParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.ResolveManifestParams) catalog.Manifest); ok {
		r0 = returnFunc(context1, resolveManifestParams)
	} else {
		r0 = ret.Get(0).(catalog.Manifest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.ResolveManifestParams) error); ok {
		r1 = returnFunc(context1, resolveManifestParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogService_ResolveManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveManifest'
type MockCatalogService_ResolveManifest_Call struct {
	*mock.Call
}

// ResolveManifest is a helper method to define mock.On call
//   - context1 context.Context
//   - resolveManifestParams catalog.ResolveManifestParams
func (_e *MockCatalogService_Expecter) ResolveManifest(context1 interface{}, resolveManifestParams interface{}) *MockCatalogService_ResolveManifest_Call {
	return &MockCatalogService_ResolveManifest_Call{Call: _e.mock.On("ResolveManifest", context1, resolveManifestParams)}
}

func (_c *MockCatalogService_ResolveManifest_Call) Run(run func(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams)) *MockCatalogService_ResolveManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.ResolveManifestParams
		if args[1] != nil {
			arg1 = args[1].(catalog.ResolveManifestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogService_ResolveManifest_Call) Return(manifest catalog.Manifest, err error) *MockCatalogService_ResolveManifest_Call {
	_c.Call.Return(manifest, err)
	return _c
}

func (_c *MockCatalogService_ResolveManifest_Call) RunAndReturn(run func(context1 context.Context, resolveManifestParams catalog.ResolveManifestParams) (catalog.Manifest, error)) *MockCatalogService_ResolveManifest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlobService creates a new instance of MockBlobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobService {
	mock := &MockBlobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobService is an autogenerated mock type for the BlobService type
type MockBlobService struct {
	mock.Mock
}

type MockBlobService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobService) EXPECT() *MockBlobService_Expecter {
	return &MockBlobService_Expecter{mock: &_m.Mock}
}

// GetBlob provides a mock function for the type MockBlobService
func (_mock *MockBlobService) GetBlob(context1 context.Context, getBlobParams cas.GetBlobParams) (cas.Blob, error) {
	ret := _mock.Called(context1, getBlobParams)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 cas.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.GetBlobParams) (cas.Blob, error)); ok {
		return returnFunc(context1, getBlobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.GetBlobParams) cas.Blob); ok {
		r0 = returnFunc(context1, getBlobParams)
	} else {
		r0 = ret.Get(0).(cas.Blob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cas.GetBlobParams) error); ok {
		r1 = returnFunc(context1, getBlobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobService_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type MockBlobService_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - context1 context.Context
//   - getBlobParams cas.GetBlobParams
func (_e *MockBlobService_Expecter) GetBlob(context1 interface{}, getBlobParams interface{}) *MockBlobService_GetBlob_Call {
	return &MockBlobService_GetBlob_Call{Call: _e.mock.On("GetBlob", context1, getBlobParams)}
}

func (_c *MockBlobService_GetBlob_Call) Run(run func(context1 context.Context, getBlobParams cas.GetBlobParams)) *MockBlobService_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cas.GetBlobParams
		if args[1] != nil {
			arg1 = args[1].(cas.GetBlobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobService_GetBlob_Call) Return(blob cas.Blob, err error) *MockBlobService_GetBlob_Call {
	_c.Call.Return(blob, err)
	return _c
}

func (_c *MockBlobService_GetBlob_Call) RunAndReturn(run func(context1 context.Context, getBlobParams cas.GetBlobParams) (cas.Blob, error)) *MockBlobService_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// OpenBlob provides a mock function for the type MockBlobService
func (_mock *MockBlobService) OpenBlob(context1 context.Context, openBlobParams cas.OpenBlobParams) (objectstore.ObjectReader, error) {
	ret := _mock.Called(context1, openBlobParams)

	if len(ret) == 0 {
		panic("no return value specified for OpenBlob")
	}

	var r0 objectstore.ObjectReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.OpenBlobParams) (objectstore.ObjectReader, error)); ok {
		return returnFunc(context1, openBlobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cas.OpenBlobParams) objectstore.ObjectReader); ok {
		r0 = returnFunc(context1, openBlobParams)
	} else {
		r0 = ret.Get(0).(objectstore.ObjectReader)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cas.OpenBlobParams) error); ok {
		r1 = returnFunc(context1, openBlobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobService_OpenBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenBlob'
type MockBlobService_OpenBlob_Call struct {
	*mock.Call
}

// OpenBlob is a helper method to define mock.On call
//   - context1 context.Context
//   - openBlobParams cas.OpenBlobParams
func (_e *MockBlobService_Expecter) OpenBlob(context1 interface{}, openBlobParams interface{}) *MockBlobService_OpenBlob_Call {
	return &MockBlobService_OpenBlob_Call{Call: _e.mock.On("OpenBlob", context1, openBlobParams)}
}

func (_c *MockBlobService_OpenBlob_Call) Run(run func(context1 context.Context, openBlobParams cas.OpenBlobParams)) *MockBlobService_OpenBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cas.OpenBlobParams
		if args[1] != nil {
			arg1 = args[1].(cas.OpenBlobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobService_OpenBlob_Call) Return(objectReader objectstore.ObjectReader, err error) *MockBlobService_OpenBlob_Call {
	_c.Call.Return(objectReader, err)
	return _c
}

func (_c *MockBlobService_OpenBlob_Call) RunAndReturn(run func(context1 context.Context, openBlobParams cas.OpenBlobParams) (objectstore.ObjectReader, error)) *MockBlobService_OpenBlob_Call {
	_c.Call.Return(run)
	return _c
}
